(PC-6396) Create pro set password screen
pass-culture/pass-culture-pro pull request #1023
Opened 2021-02-02 08:38 UTC by cgaunet

2021-02-02 09:57 UTC, victorenaud requested changes
Il y a plusieurs comportements deprecated qui sont utilisés
Codecov signale des tests manquants

2021-02-02 09:57 UTC, victorenaud commented on src/components/layout/form/fields/PasswordField.jsx
> +          name={this.props.name}
À ajouter aux proptypes

2021-02-02 09:57 UTC, victorenaud commented on src/components/layout/form/fields/PasswordField.jsx
> +    const { errors, label, name } = this.props
À ajouter aux proptypes

2021-02-02 09:57 UTC, victorenaud commented on src/components/layout/form/fields/PasswordField.jsx
> +        {this.props.showTooltip && (
À ajouter aux proptypes

2021-02-02 09:57 UTC, victorenaud commented on src/components/layout/form/fields/PasswordField.jsx
> +          validate={this.props.validate || isNotValid}
À ajouter aux proptypes

2021-02-02 09:57 UTC, victorenaud commented on src/utils/routes_map.jsx
> +  },
Normalement c'est deprecated de mettre les routes ici, on est censé les mettre dans la liste en-dessous (cf commentaire en tête de liste)

2021-02-02 09:57 UTC, victorenaud commented on src/components/pages/SetPassword/SetPassword.jsx
> +    >
C'est deprecated, si tu mets la route au bon endroit tu n'as normalement pas besoin de cela

2021-02-02 09:57 UTC, victorenaud commented on src/components/pages/SetPassword/SetPassword.jsx
> +          id="override-content-width"
Est-ce que ça ne serait pas mieux de faire une classe dédiée si in-fine on a besoin d'overidde le comportement ?

2021-02-02 09:57 UTC, victorenaud commented on src/components/pages/SetPassword/SetPassword.jsx
> +          {token && (
On a besoin d'un token pour accéder à cette page ?
Que se passe-til si on arrive sans token ?

2021-02-02 09:57 UTC, victorenaud commented on src/components/pages/SetPassword/SetPassword.jsx
> +  const { token } = parse(search)
Dans route map tu n'as pas indiqué qu'il y avait de token ? :thinking:

2021-02-02 09:57 UTC, victorenaud commented on src/utils/routes_map.jsx
> +    path: '/creation-de-mot-de-passe',
Pas de token ici, alors que tu as indiqué dans ta page avoir besoin d'un token ?

2021-02-02 09:57 UTC, victorenaud commented on src/components/pages/SetPassword/SetPassword.jsx
> +        pageName: 'sign-in',
À priori ce n'est pas le bon pageName ?

2021-02-02 09:57 UTC, victorenaud commented on src/components/pages/SetPassword/SetPassword.jsx
> +            <section className="password-reset-request-form">
C'est pas `password-reset` si ?

2021-02-02 09:57 UTC, victorenaud commented on src/components/pages/SetPassword/SetPassword.jsx
> +                          errors && errors.passwordConfirmation !== true
`errors.passwordConfirmation` est une string, pas un booléen

2021-02-02 09:57 UTC, victorenaud commented on src/components/pages/SetPassword/SetPassword.jsx
> +                            : null
Ça ne pourrait pas être remplacé par `backendErrors?.newPassword` ?

2021-02-02 09:57 UTC, victorenaud commented on src/components/pages/SetPassword/SetPassword.jsx
> +                      />
On a déjà tout cela dans le formulaire d'inscription, pourquoi le remettre ?

2021-02-02 09:57 UTC, victorenaud commented on src/components/pages/SetPassword/SetPassword.jsx
> +                        disabled={!valid}
Normalement on évite maintenant le comportement de disable un bouton de formulaire quand le formulaire n'est pas valide
Ce n'est pas très accessible
Préférer un affichage d'erreur clair

2021-02-02 09:57 UTC, victorenaud commented on src/components/pages/SetPassword/SetPassword.jsx
> +                >
Est-ce que sortir react-final-form est nécessaire ?

2021-02-02 09:57 UTC, victorenaud commented on src/components/pages/SetPassword/SetPasswordContainer.js
> +    backendErrors: get(state, `errors["${STATE_ERROR_NAME}"]`),
On évite de passer par le store pour les erreurs maintenant normalement :/

2021-02-02 09:57 UTC, victorenaud commented on src/components/pages/SetPassword/SetPasswordContainer.js
> +      })
requestData est deprecated, on a presque enfin réussi à l'enlever :pray:

2021-02-02 09:57 UTC, victorenaud commented on src/components/pages/SetPassword/SetPassword.jsx
> +  }, [showNotification, history, search, token])
Pourquoi mettre cela dans un useEffect ?

2021-02-02 09:57 UTC, victorenaud commented on src/components/pages/SetPassword/SetPassword.jsx
> +  }, [currentUser, history, backendErrors])
Je crois que normalement ceci n'est plus nécessaire si tu prends le fonctionnement standard (ie sans prendre le AppLayout deprecated
Demander à Romain de confirmer

2021-02-02 09:57 UTC, victorenaud commented on src/components/pages/SetPassword/__specs__/SetPassword.spec.jsx
> +    expect(screen.getByText('Envoyer', { selector: 'button' })).toHaveAttribute('disabled')
```suggestion
    expect(screen.getByText('Envoyer', { selector: 'button' })).toBeDisabled()
```

2021-02-02 09:57 UTC, victorenaud commented on src/components/pages/SetPassword/__specs__/SetPassword.spec.jsx
> +    expect(screen.getByText('Envoyer', { selector: 'button' })).toHaveAttribute('disabled')
```suggestion
    expect(screen.getByText('Envoyer', { selector: 'button' })).toBeDisabled()
```

2021-02-02 09:57 UTC, victorenaud commented on src/components/pages/SetPassword/__specs__/SetPassword.spec.jsx
> +    expect(screen.getByText('Envoyer', { selector: 'button' })).not.toHaveAttribute('disabled')
```suggestion
    expect(screen.getByText('Envoyer', { selector: 'button' })).toBeEnabled()
```

2021-02-02 09:57 UTC, victorenaud commented on src/components/pages/SetPassword/__specs__/SetPassword.spec.jsx
> +  it('should display the generic error message when backend errors exist', () => {
Le nom du test ne correspond pas au comportement testé

2021-02-02 09:57 UTC, victorenaud commented on src/styles/components/layout/LegalInfos/_LegalInfos.scss
> +}
:warning:  Tu surcharges pour toute l'application, il faut wrapper cela dans la classe de la page
Mais normalement `quaternary-link` est censé correspondre au styleguide, pourquoi avoir besoin de le modifier ?
Il y a peut être un soucis avec la maquette

2021-02-02 09:57 UTC, victorenaud commented on src/styles/components/layout/LegalInfos/_LegalInfos.scss
> +  font-weight: 500;
Nous ne sommes pas censés utiliser de `font-*` => se référer au styleguide pour utiliser la bonne mixin

2021-02-02 09:57 UTC, victorenaud commented on src/styles/components/layout/LegalInfos/_LegalInfos.scss
> +.legal-infos {
Il faut maintenant mettre le scss au plus proche
Se référer par exemple au scss de `Thumbnail`

2021-02-02 09:57 UTC, victorenaud commented on src/styles/components/pages/SetPassword/_SetPassword.scss
> +  .hero-body {
Ce nom vient de bulma, éviter de l'utiliser pour réduire le couplage (nous essayons d'enlever bulma)

2021-02-02 09:57 UTC, victorenaud commented on src/styles/components/pages/SetPassword/_SetPassword.scss
> +}
Est-ce que cela peut être évité ?
Le commentaire est redondant avec le nom de l'id

2021-02-02 09:57 UTC, victorenaud commented on src/styles/components/pages/SetPassword/_SetPassword.scss
> +.password-set-request-form,
Idem que plus haut, mettre cela au plus proche du composant

2021-02-02 10:03 UTC, cgaunet commented on src/components/pages/SetPassword/SetPassword.jsx
> +                          errors && errors.passwordConfirmation !== true
C'est aussi un booléen dans certains cas :)
Je ne sais pas pourquoi final form fait ça, mais il le fait...

2021-02-02 10:04 UTC, cgaunet commented on src/components/pages/SetPassword/SetPassword.jsx
> +                            : null
Si on est compatible là-dessus je vais me faire un plaisir de changer ça ;)

2021-02-02 10:04 UTC, cgaunet commented on src/components/pages/SetPassword/SetPassword.jsx
> +                      />
Parce que les pros qui arrivent ici ne sont pas passés par le formulaire d'inscription

2021-02-02 10:05 UTC, cgaunet commented on src/components/pages/SetPassword/SetPassword.jsx
> +                        disabled={!valid}
Je me suis inspiré des autres formulaires, je peux très facilement enlever ça du coup

2021-02-02 10:05 UTC, cgaunet commented on src/components/pages/SetPassword/SetPassword.jsx
> +                >
Comment ça ?

2021-02-02 10:06 UTC, cgaunet commented on src/components/pages/SetPassword/SetPassword.jsx
> +  }, [showNotification, history, search, token])
Pourquoi pas ? Je comprends pas :)
UseEffect permet d'éviter d'appeler ça tant que les dépendances n'ont pas changé, c'est mieux

2021-02-02 10:06 UTC, cgaunet commented on src/components/pages/SetPassword/SetPassword.jsx
> +  }, [currentUser, history, backendErrors])
Cool, je peux tester voir si ça fonctionne en effet

2021-02-02 10:07 UTC, cgaunet commented on src/components/pages/SetPassword/__specs__/SetPassword.spec.jsx
> +    expect(screen.getByText('Envoyer', { selector: 'button' })).toHaveAttribute('disabled')
À voir si on supprime le comportement

2021-02-02 10:07 UTC, cgaunet commented on src/components/pages/SetPassword/__specs__/SetPassword.spec.jsx
> +    expect(screen.getByText('Envoyer', { selector: 'button' })).toHaveAttribute('disabled')
Idem du coup

2021-02-02 10:07 UTC, cgaunet commented on src/components/pages/SetPassword/__specs__/SetPassword.spec.jsx
> +    expect(screen.getByText('Envoyer', { selector: 'button' })).not.toHaveAttribute('disabled')
Idem

2021-02-02 10:07 UTC, cgaunet commented on src/styles/components/layout/LegalInfos/_LegalInfos.scss
> +  font-weight: 500;
Ah yes, j'ai repris le code existant, je vais changer ça

2021-02-02 10:08 UTC, cgaunet commented on src/styles/components/layout/LegalInfos/_LegalInfos.scss
> +.legal-infos {
je vais regarder ça

2021-02-02 10:08 UTC, cgaunet commented on src/styles/components/pages/SetPassword/_SetPassword.scss
> +  .hero-body {
je check si ça casse rien :+1:

2021-02-02 10:09 UTC, cgaunet commented on src/styles/components/pages/SetPassword/_SetPassword.scss
> +}
Je peux enlever le commentaire, en revanche j'ai essayé de faire autrement, à moins de mettre 4 classes de suites pour avoir un bon niveau de spécificité, le style est difficilement "overridable"

2021-02-02 10:10 UTC, cgaunet commented
> Il y a plusieurs comportements deprecated qui sont utilisés
> Codecov signale des tests manquants

Je comprends pas pour le codecov, tu voudrais rajouter quels tests par exemple ?

2021-02-02 10:11 UTC, rlecellier commented on src/components/pages/SetPassword/SetPassword.jsx
> +  }, [currentUser, history, backendErrors])
Tu dire `Main` deprecated, on vise à utiliser `AppLayout` partout. 

Parcontre le redirect est bien la manière de faire.
On à un redirect qui est fait lorsque le user n'est pas dans le store ici : https://github.com/pass-culture/pass-culture-pro/blob/master/src/app/App.jsx#L30
Et on utiliser un `redirectLoggedUser` pour les page qui ne doivent pas etre accesible pour les utilisateurs logé, comme ici: https://github.com/pass-culture/pass-culture-pro/blob/master/src/components/pages/Signin/Signin.jsx#L19

2021-02-02 10:11 UTC, cgaunet commented on src/components/pages/SetPassword/SetPasswordContainer.js
> +    backendErrors: get(state, `errors["${STATE_ERROR_NAME}"]`),
Dû au requestData du coup, legacy oblige j'ai copié-collé la mauvaise partie du code

2021-02-02 10:13 UTC, cgaunet commented on src/components/pages/SetPassword/SetPassword.jsx
> +  }, [currentUser, history, backendErrors])
Du coup je compte resolve sans faire de modifs ici, dites moi si je me trompe

2021-02-02 10:18 UTC, cgaunet commented on src/components/pages/SetPassword/SetPassword.jsx
> +          id="override-content-width"
Pb de spécifcité si je passe par une simple classe

2021-02-02 11:06 UTC, cgaunet commented on src/components/pages/SetPassword/SetPassword.jsx
> +        pageName: 'sign-in',
Ça permet de réutiliser le même css sur les différentes page sign in, reset password etc.
Le naming n'est pas bon mais j'aimerais éviter d'embarquer encore d'autre refactos :)

2021-02-02 11:17 UTC, victorenaud commented on src/components/pages/SetPassword/SetPassword.jsx
> +  }, [showNotification, history, search, token])
Parce que du coup le code est asynchrone
Ça veut dire qu'on va afficher la page à l'utilisateur PUIS on va le rediriger
Visuellement c'est pas génial :(

Alors que `search` est là dès le début, donc on pourrait directement mettre ça dans le code du composant en mode "si tu as cette condition, tu rediriges l'utilisateur sans attendre"

2021-02-02 11:17 UTC, victorenaud commented on src/components/pages/SetPassword/SetPassword.jsx
> +  }, [currentUser, history, backendErrors])
Je me pose juste la question de mettre ça dans le useEffect (pareil qu'au-dessus)
Si on a l'info dès l'init du composant, ça permet de le rediriger sans flicker de la page
Si tu préfères garder le useEffect, il faut mettre à jour les dépendances, `backendErrors` n'est pas nécessaire

2021-02-02 11:17 UTC, victorenaud commented on src/components/pages/SetPassword/SetPassword.jsx
> +          id="override-content-width"
Je ne suis pas certain de comprendre
Si tu fais un `.set-password-page .content {width:...}` ça devrait suffire pour le faire sans id non ? :thinking:

2021-02-02 11:17 UTC, victorenaud commented on src/components/pages/SetPassword/SetPassword.jsx
> +                >
Ça me donne l'impression de sortir la grosse artillerie pour un simple formulaire de deux inputs, et perdre la maitrise du submit
Récemment on a plutôt fait le choix de faire sans, d'où ma question
Mais vu que tu as dit ailleurs que tu avais c/c d'autres composants du coin, je comprends mieux :smile: 

Je te laisse juger si tu préfères faire ça en vanilla ou avec react-final-form (potentillement tu n'as pas le choix à cause de `PasswordField` :disappointed: )

2021-02-02 11:17 UTC, victorenaud commented on src/components/pages/SetPassword/SetPassword.jsx
> +                          errors && errors.passwordConfirmation !== true
Mais du coup je ne comprends pas la logique

`errors.passwordConfirmation !== true` va être vrai dans tous les cas SAUF SI c'est `true`
Donc ta condition est vraie également s'il a pour valeur `""`, `null` ou `undefined`, c'est pas gênant ?

(sinon mon coeur a saigné sur ce comportement de react-final-form :disappointed: )

2021-02-02 11:17 UTC, victorenaud commented on src/styles/components/pages/SetPassword/_SetPassword.scss
> +}
Ah, comme je disais plus haut `.set-password-form .content {width:...}` n'est pas assez spécifique ?
Vu que tu restreins à cette page uniquement

2021-02-02 16:00 UTC, cgaunet commented on src/styles/components/pages/SetPassword/_SetPassword.scss
> +}
Non :/ Le style prend 4 classes ailleurs, et j'ai pas forcément envie de tout casser le jour où ils changent un nom de classe du layout, ici ça permet l'override sans créer un fort couplage avec le CSS du layout

2021-02-02 16:03 UTC, cgaunet commented on src/components/pages/SetPassword/SetPassword.jsx
> +                          errors && errors.passwordConfirmation !== true
Je trouve pas ça gênant de donner `null` ou `undefined`, je peux changer ça pour `""`

(Oui, je vais quand même confirmer que ce n'était pas dû à ma console navigateur ouverte, ça m'a joué des tours sur d'autres endroits...)

2021-02-02 16:05 UTC, cgaunet commented on src/components/pages/SetPassword/SetPassword.jsx
> +  }, [showNotification, history, search, token])
Vendu

2021-02-02 16:06 UTC, cgaunet commented on src/components/pages/SetPassword/SetPassword.jsx
> +                >
Alors, en effet, déjà je n'ai pas le choix à cause du PasswordField, mais je trouve ça aussi sympa d'éviter de réinventer les logiques propres au formulaires de touched, de validation côté champ ou au submit etc
Je trouve que ça apporte pas mal de choses :)

2021-02-02 16:07 UTC, cgaunet commented on src/components/pages/SetPassword/SetPassword.jsx
> +  }, [currentUser, history, backendErrors])
Aussi ok avec ça du coup

2021-02-03 09:33 UTC, victorenaud commented on src/components/pages/SetPassword/SetPassword.jsx
> +        pageName: 'sign-in',
Ok :+1:

2021-02-03 09:33 UTC, victorenaud commented on src/components/pages/SetPassword/SetPassword.jsx
> +                >
Ok :+1:

2021-02-03 09:33 UTC, victorenaud commented on src/components/pages/SetPassword/SetPassword.jsx
> +                          errors && errors.passwordConfirmation !== true
Mon soucis n'est pas sur le `null`, `""` ou `undefined`
Je m'interrogeais sur si on avait le comportement attendu
En effet, ta condition est vraie (et donc on tente d'afficher `errors.passwordConfirmation`) si `errors.passwordConfirmation` vaut une de ces trois valeurs

Donc je me demandais si c'était normal

Parce que `errors.passwordConfirmation !== true` ne va être false que si on a `errors.passwordConfirmation` qui vaut `true`, ce qui est un cas très restrictif

2021-02-03 09:33 UTC, victorenaud commented on src/styles/components/pages/SetPassword/_SetPassword.scss
> +}
Tristesse et chocolat
Ok alors :+1:

2021-02-03 14:09 UTC, cgaunet commented on src/components/pages/SetPassword/SetPassword.jsx
> +                          errors && errors.passwordConfirmation !== true
Avec le nouveau comportement (i.e sans le disable c'est OK)

2021-02-03 14:29 UTC, victorenaud approved these changes

2021-02-03 14:29 UTC, victorenaud commented on src/components/pages/SetPassword/SetPassword.jsx
> +export const DIFFERENT_PASSWORDS_ERROR_MESSAGE = 'Les deux mots de passe ne sont pas identiques'
Il y a des points à certaines fin de phrases et pas à d'autres, c'est normal ?
#tatillon

Mais sinon j'aime bien ce regroupement, c'est plus clair
Voire on pourrait sortir cela dans un `_constants.js` mais je te laisse juger

2021-02-03 14:29 UTC, victorenaud commented on src/components/pages/SetPassword/SetPassword.jsx
> +    showNotification('error', 'Votre lien de création de mot de passe est invalide')
Pourquoi ne pas avoir mis ce message en constant également ?

2021-02-03 14:29 UTC, victorenaud commented on src/components/pages/SetPassword/SetPassword.jsx
> +      if (backendErrors && backendErrors.newPassword) {
Tu peux utiliser la même logique qu'au-dessus pour simplifier

```suggestion
      if (backendErrors?.newPassword) {
```

2021-02-03 14:29 UTC, victorenaud commented on src/components/pages/SetPassword/__specs__/SetPassword.spec.jsx
> +            <SetPassword />
Pourquoi ne pas avoir mis `<SetPasswordContainer>` ?
(Si on en a discuté j'ai oublié, sorry :sweat_smile: )

2021-02-03 14:29 UTC, victorenaud commented on src/components/pages/SetPassword/__specs__/SetPassword.spec.jsx
> +  it('should redirect the user to structure page', async () => {
```suggestion
  it('should redirect the user to structure page if it is already logged', async () => {
```

2021-02-03 14:29 UTC, victorenaud commented on src/components/pages/Signup/SignupForm/SignupForm.jsx
> +                  errors={errors ? errors.password : null}
Remplacer par `errors?.password` ne fonctionnait pas ?

2021-02-03 14:32 UTC, cgaunet commented on src/components/pages/SetPassword/__specs__/SetPassword.spec.jsx
> +            <SetPassword />
C'est le container, mais c'est un export default j'ai pas changé le naming, je peux le changer si c'est plus clair

2021-02-03 14:33 UTC, cgaunet commented on src/components/pages/SetPassword/__specs__/SetPassword.spec.jsx
> +  it('should redirect the user to structure page', async () => {
Pas forcément fan d'écrire toutes les conditions dans le titre du test :)
Sinon on peut faire le même exercice pour tous les autres et ça peut donner des noms très très long :sweat_smile: 
Du style: "should display password error message if submit fails on server side and no form validation error"

2021-02-03 14:35 UTC, cgaunet commented on src/components/pages/Signup/SignupForm/SignupForm.jsx
> +                  errors={errors ? errors.password : null}
Parce que j'ai envie de modifier tous les composants que je modifie au passage là si c'est de la syntaxe.
Il y a d'autres problèmes plus importants côté SignupForm mais je préfère éviter d'embarquer trop de modifs hors scope.

2021-02-03 14:36 UTC, cgaunet commented on src/components/pages/SetPassword/SetPassword.jsx
> +    showNotification('error', 'Votre lien de création de mot de passe est invalide')
C'était prévu, j'ai zappé

2021-02-03 14:36 UTC, cgaunet commented on src/components/pages/SetPassword/SetPassword.jsx
> +export const DIFFERENT_PASSWORDS_ERROR_MESSAGE = 'Les deux mots de passe ne sont pas identiques'
Pour le constants, pour l'instant je préfère garder ça ici, ça reste 5 lignes donc si ça peut être au plus près je suis content en tant que dev

2021-02-03 14:43 UTC, cgaunet commented on src/components/pages/SetPassword/SetPassword.jsx
> +export const DIFFERENT_PASSWORDS_ERROR_MESSAGE = 'Les deux mots de passe ne sont pas identiques'
Pour le point j'ai en ajouté un au message de succès, pour celui du formulaire ça ferait bizarre par contre

2021-02-03 14:53 UTC, merged