Rlecellier/6524 new home offerer details
pass-culture/pass-culture-pro pull request #1055
Opened 2021-02-08 16:56 UTC by rlecellier

Une première étape en draft avec le squelette de la page en css:

zeplin: https://app.zeplin.io/project/5e05ce53fdf73e9a53ed33e9/screen/601b08fb5ca097231be9c0ca

![onBoarding-squelette](https://user-images.githubusercontent.com/139848/107253734-e8b6bb80-6a36-11eb-9d39-802b4e1eae80.png)

2021-02-10 10:35 UTC, victorenaud requested changes
Le composant ExpandableBox n'est pas mergeable en l'état car il n'est pas accessible

2021-02-10 10:35 UTC, victorenaud commented on src/components/pages/Home/Offerers.jsx
> +      setSelectedOfferer(receivedOfferers[0])
Il faudrait ordonner la liste par ordre alphabétique avant non ?

2021-02-10 10:35 UTC, victorenaud commented on src/components/pages/Home/Offerers.jsx
> +  const handleChangeOfferer = useCallback(
```suggestion
  const selectOfferer = useCallback(
```

2021-02-10 10:35 UTC, victorenaud commented on src/components/pages/Home/Homepage.scss
> +.homepage {
Le flex fait que si le nom / prenom / email est trop long, la carte va déborder sur la suivante au niveau du profil

2021-02-10 10:35 UTC, victorenaud commented on src/components/pages/Home/Homepage.scss
> +.homepage {
Le siège social est à la ligne chez moi, alors qu'il devrait être sur la même ligne

2021-02-10 10:35 UTC, victorenaud commented on src/components/pages/Home/Offerers.jsx
> +            <div className="h-card-header-block">
Ça fait un squelette vachement complexe, surtout que 3 de ces divs ne se referment qu'à la fin
Pourquoi ne pas avoir fait qu'une seule div du coup ?

2021-02-10 10:35 UTC, victorenaud commented on src/components/pages/Home/Offerers.jsx
> +          <div className="h-card-inner">
Idem ici, on a 3 divs qui se contentent d'envelopper un titre et une div, c'est trop... :/

2021-02-10 10:35 UTC, victorenaud commented on src/components/pages/Home/Offerers.jsx
> +  return (
On pourrait sortir dans des composants le détail de la structure et le détail des lieux
Ça permettrait de concentrer ce composant sur la logique de récupération, et les autres composants seront purement graphiques
Ça serait plus dans le sens de ce qu'on avait dit au point papotage tech pro

2021-02-10 10:35 UTC, victorenaud commented on src/components/pages/Home/Profile.jsx
> +          <div className="h-card-inner">
Même chose ici, 3 divs pour envelopper du contenu :/

2021-02-10 10:35 UTC, victorenaud commented on src/components/pages/Home/Usages.jsx
> +          tabIndex={0}
Tu brises l'objectif du tabindex
L'objectif est de pouvoir sélectionner ce "bouton" au clavier pour pouvoir l'ouvrir
Ce n'est pas le cas

Ce composant n'est donc pas accessible

2021-02-10 10:35 UTC, victorenaud commented on src/components/pages/Home/Usages.jsx
> +          tabIndex={-1}
Idem ici

2021-02-10 10:35 UTC, victorenaud commented on src/components/pages/Home/__specs__/Homepage.spec.jsx
> +      </MemoryRouter>
Est-ce qu'on a besoin du `MemoryRouter` ici ?

2021-02-10 10:35 UTC, victorenaud commented on src/components/pages/Home/__specs__/Homepage.spec.jsx
> +      await renderHomePage()
Vu qu'on a une seule ligne, je pense qu'il vaudrait mieux la laisser dans chaque test plutôt que la cacher dans un beforeEach dans ce cas

2021-02-10 10:35 UTC, victorenaud commented on src/components/pages/Home/ExpandableBox/ExpandableBox.jsx
> +        <h4 className="eb-title">
Pourquoi mettre des h4 alors que le niveau du dessus est un h2 ?

2021-02-10 10:35 UTC, victorenaud commented on src/components/pages/Home/__specs__/Homepage.spec.jsx
> +        })
Je préfère laisser cela dans le test

2021-02-10 10:35 UTC, victorenaud commented on src/utils/testHelpers.js
> +
Qu'est-ce donc ?

2021-02-10 11:06 UTC, rlecellier reviewed
Pear review on going !
Partial !

2021-02-10 11:06 UTC, rlecellier commented on src/components/pages/Home/Homepage.scss
> +.homepage {
* il prevoit tout les cas utilisé sur cette maquette;
* flex est fixer dans la PR sur le profile
* il faut trouve une solution pour le DD car le flot casse effectivement :/

2021-02-10 11:06 UTC, rlecellier commented on src/components/pages/Home/Homepage.scss
> +    overflow: hidden;
ca permet de ne pas reporter les border-radius sur les enfant, ici pour la bordure coloré a gauche.

2021-02-10 16:13 UTC, rlecellier commented on src/components/pages/Home/Homepage.scss
> +        margin-left: rem(24px); // in case it's inside a section-row with multiple cards
ici c'est claire. mais peut etre qu'il faudrait plus de commentaires sur les autres classes.
les section-row (defini juste desssu) sont en flex-direction row.
Quand on à plusieurs cartes dedant, on veux qu'elle ai toute 24 de marge entre elles.

2021-02-10 16:13 UTC, rlecellier commented on src/components/pages/Home/Offerers.jsx
> +  const handleChangeOfferer = useCallback(
j'aime bien ajouter des "handle" en prefix que fonction qui gèrent des `event` js

2021-02-10 16:13 UTC, rlecellier commented on src/components/pages/Home/Offerers.jsx
> +  return (
Pourquoi pas, quand on fera l'affichage de la liste des `venues`
Je n'etait pas la au point papot pro, sorry.

2021-02-10 16:13 UTC, rlecellier commented on src/components/pages/Home/Offerers.jsx
> +            <div className="h-card-header-block">
```
card // le container, qui vas definir sont comportement exterieur (border radius, ombres, eventueles marges relative au siblings)
- card inner // le comportement interne, le padding, le style de la bordure coloré a gauche
- - card header // comportement exterieur du header de la cart
- - - header block // un bloc possible du header, avec sont comportement interieur et relatif au voisin
- - - card action // pareil que  block
- - card cols // container de colonne
- - -  col // une colone
```

2021-02-10 16:13 UTC, rlecellier commented on src/components/pages/Home/Offerers.jsx
> +          <div className="h-card-inner">
je trouve pas, ca sépare les roles.

2021-02-10 16:13 UTC, rlecellier commented on src/components/pages/Home/Usages.jsx
> +          tabIndex={0}
cf: https://github.com/pass-culture/pass-culture-pro/pull/1067

2021-02-10 16:13 UTC, rlecellier commented on src/components/pages/Home/__specs__/Homepage.spec.jsx
> +      </MemoryRouter>
oui, a cause du liens vers la modification de structure qui utilise Link et donc react.router

2021-02-10 16:13 UTC, rlecellier commented on src/components/pages/Home/__specs__/Homepage.spec.jsx
> +      await renderHomePage()
ca rend chaque test plus simple.
ici on à une seul ligne car le cas testé est basic mais en suivant le meme schéma pour les autres cas à tester on peut avoir des mise en place plus complexe.

2021-02-10 16:13 UTC, rlecellier commented on src/components/pages/Home/__specs__/Homepage.spec.jsx
> +        })
JE pense qu'on peut vouloir tester plusieurs choses quand un offerer change, comme à terme la liste des venue, autant définir le comportement initial une bonne fois et facilement ajouter des choses testé pour celui ci.

2021-02-10 16:13 UTC, rlecellier commented on src/utils/testHelpers.js
> +
ca permet de donner à jest les css.
On peu ainsi utilisé `expect(monElement).isVisible()`

2021-02-11 09:01 UTC, victorenaud approved these changes
Par contre ça ne compile pas

2021-02-11 13:37 UTC, merged