(PC-7747): Redirect user depending on homepage ff
pass-culture/pass-culture-pro pull request #1197
Opened 2021-03-24 09:49 UTC by asagot-ansa

2021-03-24 13:34 UTC, schable approved these changes

2021-03-24 16:25 UTC, rlecellier requested changes

2021-03-24 16:25 UTC, rlecellier commented on src/components/pages/Offerer/OffererCreation/OffererCreationContainer.js
> +  redirectAfterSubmit: isNewHomepageActive => {
retirer l'argument `isNewHomepageActive` et bouger cette fonction dans un `mapDispatchToProps`

2021-03-24 16:27 UTC, rlecellier approved these changes

2021-03-25 10:32 UTC, rlecellier approved these changes

2021-03-25 14:39 UTC, merged