(PC-8753) Add api key generation
pass-culture/pass-culture-pro pull request #1383
Opened 2021-06-29 16:00 UTC by viconnex

![image](https://user-images.githubusercontent.com/22373097/123830690-d2d16680-d903-11eb-84c6-7db9a05378e8.png)

2021-06-30 12:26 UTC, viconnex commented on src/components/pages/Offerers/Offerer/OffererDetails/ApiKey/ApiKey.jsx
> +        setNewGeneratedKeys(newKeys)
setNewGeneratedKeys((prev)=>[...prev, newKeys])

2021-06-30 12:43 UTC, gael-boyenval requested changes

2021-06-30 12:43 UTC, gael-boyenval commented on src/components/pages/Offerers/Offerer/OffererDetails/ApiKey/ApiKey.jsx
> +        setNewGeneratedKeys(newKeys)
`setNewGeneratedKeys((prevKeys) => [...prevKeys, newKeys])` (et virer les deux lignes au dessus)

2021-06-30 12:43 UTC, gael-boyenval commented on src/components/pages/Offerers/Offerer/OffererDetails/ApiKey/ApiKey.jsx
> +      .then(apiKey => {
perso je préfère la syntaxe async / await mais c'est assez perso... en plus, la fonction suivante utilise async await, du coup je pense que tu peux choisir une syntaxe qui te plait et la conserver à travers le fichier.

2021-06-30 12:43 UTC, gael-boyenval commented on src/components/pages/Offerers/Offerer/OffererDetails/ApiKey/ApiKey.jsx
> +      .then(apiKey => {
tu ans déjà une prop qui s'appelle `apiKey` c'est plus clair si on définit un nouveau nom ici

2021-06-30 12:43 UTC, gael-boyenval commented on src/components/pages/Offerers/Offerer/OffererDetails/ApiKey/__specs__/ApiKey.spec.jsx
> +    expect(screen.getByText('key-prefix1********')).toBeInTheDocument()
y'a pas de message d'erreur ? 
tester le message d'erreur de la notification. 
là c'est pas clair ce que tu teste. (qu'il n'y a pas de changement de page ?)

2021-06-30 12:43 UTC, gael-boyenval commented on src/components/pages/Offerers/Offerer/OffererDetails/ApiKey/__specs__/ApiKey.spec.jsx
> +    )
et si j'essai quand même d'en créer un autre ? 
mon bouton est disabled ? que se passe-t-il quand j'atteins la limite ?
je suis pas hyper fan de tester la class `api-key-title__counter--error` car c'est un détail d'implémentation.

2021-06-30 12:43 UTC, gael-boyenval commented on src/components/pages/Offerers/Offerer/OffererDetails/OffererDetails.jsx
> +          apiKey={offerer.apiKey}
du coup comme on en a disctuté, se serait peut-être plus clair si tu déstructurais tes propos ici, car apiKey n'est pas un mot très représentatif de son contenu.

un truc comme ça serait plus clair (sans avoir à changer la réponse de l'api) : 

```
<ApiKey
   savedApiKeys={offerer.apiKey.prefixes}
   maxAllowedApiKeys={offerer.apiKey.maxAllowed}
   offererId={offerer.id}
/>
```

2021-06-30 12:43 UTC, gael-boyenval commented on src/styles/components/pages/Offerer/ApiKey/_ApiKey.scss
> +      &__text {
ici la syntaxe c'est du BEM, tu ne peut pas wrapper un `element` dans un autre `élément` => remonte ta classe d'un niveau : PAS `XXX__item_text` MAIS `XXX__text`, si tu veux garder la sémantique du parent : `XXX__item-text`

2021-06-30 12:43 UTC, gael-boyenval commented on src/styles/components/pages/Offerer/ApiKey/_ApiKey.scss
> +  .api-key-warning__visible {
ici visible me semble plutôt avoir un rôle de modifier du coup `.api-key-warning--visible`, mais du coup, où est son bloc ?

2021-06-30 12:49 UTC, asagot-ansa commented on src/components/pages/Offerers/Offerer/OffererDetails/ApiKey/ApiKey.jsx
> +            isMaxAllowedReached ? ' api-key-title__counter--error' : ''
Dans la codebase pro nos className ne comportent aucun `_` , par souci d'homogénéité ce serait cool de les remplacer par des tirets classiques :)

2021-06-30 12:49 UTC, asagot-ansa commented on src/components/pages/Offerers/Offerer/OffererDetails/ApiKey/ApiKey.jsx
> +  function generateApiKey() {
On a tendance a utiliser des arrow function en mode useCallback plutôt que des `function`.
A toi de voir si tu veux rester dans l'homogénéité ou casser les codes :D

2021-06-30 12:49 UTC, asagot-ansa commented on src/components/pages/Offerers/Offerer/OffererDetails/ApiKey/ApiKey.jsx
> +  const copyKey = apiKey => async () => {
Petit saut de ligne entre 24 et 25 please

2021-06-30 12:49 UTC, asagot-ansa commented on src/components/pages/Offerers/Offerer/OffererDetails/ApiKey/ApiKey.jsx
> +  const generatedKeysCount = apiKey.prefixes.length + newGeneratedKeys.length
Petit saut de ligne entre 32 et 33 please :D

2021-06-30 12:49 UTC, asagot-ansa commented on src/components/pages/Offerers/Offerer/OffererDetails/ApiKey/__specs__/ApiKey.spec.jsx
> +  it('should display api keys and generate new key', async () => {
Ce serait cool si tu pouvais rajouter les // given // when // then avec de préférence une seule action dans le when

2021-06-30 12:49 UTC, asagot-ansa commented on src/components/pages/Offerers/Offerer/OffererDetails/ApiKey/__specs__/ApiKey.spec.jsx
> +  it('should display an error when the api call fails', async () => {
Un petit saut de ligne entre chaque test please

2021-06-30 12:49 UTC, asagot-ansa commented on src/styles/components/pages/Offerer/ApiKey/_ApiKey.scss
> +        margin-left: 16px;
```suggestion
        margin-left: rem(16px);
```

2021-06-30 12:49 UTC, asagot-ansa commented on src/styles/mixins/_fonts.scss
> +@mixin bold() {
Est-ce que tu en as parlé avec un UX de pourquoi on a une typo qui est plus grasse que les autres et est-ce que c'est vraiment nécessaire ? Nos mixins sont là justement pour qu'on reste "dans le cadre" donc à voir si on a vraiment besoin d'en rajouter :)

2021-06-30 12:49 UTC, asagot-ansa commented on src/components/pages/Offerers/Offerer/OffererDetails/ApiKey/ApiKey.jsx
> +      .catch(() => showNotification('error', "Une erreur s'est produite"))
On a vu avec un PO pour le message d'erreur ? On a pas un peu plus user-friendly ?

2021-06-30 12:49 UTC, asagot-ansa commented on src/components/pages/Offerers/Offerer/OffererDetails/ApiKey/ApiKey.jsx
> +        {'Générer un clé API'}
J'ai vu sur l'US qu'il était indiqué de mettre un loader dans le bouton jusqu'au retour du call backend - je ne le vois pas ici, j'ai peut-être raté un truc ? :)

2021-06-30 15:59 UTC, viconnex commented on src/components/pages/Offerers/Offerer/OffererDetails/ApiKey/ApiKey.jsx
> +  function generateApiKey() {
ça n'a pas trop de sens d'utiliser un useCallback ici :/ 
mais ok

2021-06-30 16:06 UTC, viconnex commented on src/components/pages/Offerers/Offerer/OffererDetails/ApiKey/ApiKey.jsx
> +      .catch(() => showNotification('error', "Une erreur s'est produite"))
non
je rajoute "veuillez réessayer", un peu comme dans INVALID_FORM_MESSAGE

2021-06-30 16:35 UTC, viconnex commented on src/styles/mixins/_fonts.scss
> +@mixin bold() {
effectivement c'était plus du font-weight: 600

2021-06-30 16:44 UTC, viconnex commented on src/components/pages/Offerers/Offerer/OffererDetails/ApiKey/__specs__/ApiKey.spec.jsx
> +    )
oui c'est mieux de tester que le bouton est disabled

2021-07-01 07:26 UTC, dbaty commented on src/components/pages/Offerers/Offerer/OffererDetails/ApiKey/ApiKey.jsx
> +      showNotification('success', 'Clé copiée dans le presse papier !')
```suggestion
      showNotification('success', 'Clé copiée dans le presse-papier !')
```

2021-07-01 07:26 UTC, dbaty commented on src/components/pages/Offerers/Offerer/OffererDetails/ApiKey/ApiKey.jsx
> +      showNotification('error', 'Impossible de copier la clé dans le presse papier')
```suggestion
      showNotification('error', 'Impossible de copier la clé dans le presse-papier')
```

2021-07-01 09:22 UTC, viconnex commented on src/components/pages/Offerers/Offerer/OffererDetails/ApiKey/__specs__/ApiKey.spec.jsx
> +    expect(screen.getByText('key-prefix1********')).toBeInTheDocument()
test sur le showNotification ajouté

2021-07-01 09:45 UTC, gael-boyenval approved these changes

2021-07-01 09:45 UTC, gael-boyenval commented on src/components/pages/Offerers/Offerer/OffererDetails/ApiKey/ApiKey.jsx
> +        disabled={isMaxAllowedReached}
`isMaxAllowedReached || isGeneratingKey` maybe

2021-07-01 14:08 UTC, merged