(PC-8554): Show confirmation dialog before importing stocks from provider
pass-culture/pass-culture-pro pull request #1418
Opened 2021-07-29 10:14 UTC by yacine-pc

2021-07-30 12:32 UTC, rlecellier requested changes
Quelques changements dans le découpage afin d'éviter d'avoir un composant `VenueProvidersManager` qui grossie sans fin.

2021-07-30 12:32 UTC, rlecellier commented on src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/StocksProviderForm/StocksProviderForm.jsx
> +  const handleFormSubmit = useCallback(event => {
```suggestion
  const handleOpenConfirmDialog = useCallback(event => {
```

2021-07-30 12:32 UTC, rlecellier commented on src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/StocksProviderForm/StocksProviderForm.jsx
> +  const abortImportingFromProvider = useCallback(() => {
```suggestion
  const handleCloseConfirmDialog = useCallback(() => {
```

2021-07-30 12:32 UTC, rlecellier commented on src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/StocksProviderForm/StocksProviderForm.jsx
> +  const confirmImportingFromProvider = useCallback(() => {
```suggestion
  const handleFormSubmit = useCallback(() => {
```

2021-07-30 12:32 UTC, rlecellier commented on src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/StocksProviderForm/StocksProviderForm.jsx
> +        <DialogBox
à déplacer dans un composant dédié `.../VenueEdition/VenueProviderManager/ConfirmDialog/ConfirmDialog.jsx`


```suggestion
      { isConfirmDialogOpened && (
        <ConfirmDialog 
         onConfirm={handleFormSubmit} 
         onCancel={handleCloseConfirmDialog}
        /> 
      )}
```

2021-07-30 12:32 UTC, rlecellier commented on src/styles/components/pages/Venue/VenueProvidersManager/VenueProvidersManager.scss
> +.provider-import-confirmation-dialog {
`VenueProvidersManager/ConfirmDialog.scss`

2021-07-30 12:32 UTC, rlecellier commented on src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/StocksProviderForm/StocksProviderForm.jsx
> +  const confirmButtonRef = useRef()
Je ne vois pas ou cette `ref` est utilisée.

2021-07-30 12:50 UTC, rlecellier commented on src/styles/components/pages/Venue/VenueProvidersManager/VenueProvidersManager.scss
> +.provider-import-confirmation-dialog {
Changement de plans https://github.com/pass-culture/pass-culture-pro/pull/1420 à été mergé, ces styles doivent etre dans le dossier `src/components/.../VenueProvidersManager/ConfirmDialog/ConfirmDialog.scss` puis importé depuis `ConfirmDialog/ConfirmDialog.jsx`

2021-07-30 15:25 UTC, yacine-pc commented on src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/StocksProviderForm/StocksProviderForm.jsx
> +  const confirmButtonRef = useRef()
La `ref` permettait de focus le bouton de confirmation au lieu du lien FAQ qui est focus par défaut, du coup il s'affiche en noir contrairement au template.

2021-08-02 12:31 UTC, rlecellier approved these changes

2021-08-02 12:31 UTC, rlecellier commented on src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/ConfirmDialog/ConfirmDialog.jsx
> +const ConfirmDialog = ({ onConfirm, onCancel }) => {
trop bien :)

2021-08-02 12:50 UTC, merged