Pc 11372 improve bookings perf
pass-culture/pass-culture-pro pull request #1548
Opened 2021-11-02 08:20 UTC by asagot-ansa

2021-11-03 10:52 UTC, gael-boyenval reviewed
à discuter ensemble, j'ai peut-être loupé quelque chose

2021-11-03 10:52 UTC, gael-boyenval commented on src/components/pages/Bookings/BookingsRecap.jsx
> +    if (result.status === 200) {
et sinon ?

2021-11-03 10:52 UTC, gael-boyenval commented on src/components/pages/Bookings/BookingsRecap.jsx
> +    if (result.status === 200) {
une petite notification avec un message d'erreur peut-être ?

2021-11-03 10:52 UTC, gael-boyenval commented on src/components/pages/Bookings/BookingsRecap.jsx
> +    const result = await fetch(url, { credentials: 'include' })
en attendant, on affiche rien à l'utilisateur ? se serait bien d'avoir un loader quelque part car ça peut prendre pas mal de temps, et/ou de désactiver le bouton afin qu'il n'envoi pas X requêtes côté serveur.

2021-11-03 10:52 UTC, gael-boyenval commented on src/components/pages/Bookings/BookingsRecap.jsx
> +  }, [])
et si on sortait cette fonction du composant, car elle est pure.

```suggestion

// dans un fichier à part
const downLoadCSVFile = async queryParams => {
    const url = new URL(`${API_URL}/bookings/csv`)
    const params = pcapi.buildFetchParams(queryParams)
    Object.keys(params).forEach(key => url.searchParams.append(key, params[key]))
    try {
      const result = await fetch(url, { credentials: 'include' })
    
      if (result.status === 200) {
        const text = await result.text()
        const fakeLink = document.createElement('a')
        const blob = new Blob([text], { type: "text/csv" })
        const date = new Date().toISOString()
        fakeLink.href = URL.createObjectURL(blob)
        fakeLink.setAttribute('download', `reservations_pass_culture-${date}.csv`)
        document.body.appendChild(fakeLink)
        fakeLink.click()
        document.body.removeChild(fakeLink)
      
        return 'success'
      }
      
       return 'error' // on checkera peut-être plusieurs cas d'erreur
    } catch (e) {
       return 'error' // en cas de 500 ou tout autre erreur 
    }
  }


// dans le composant
  const downloadBookingsCSV = useCallback(async queryParams => {
    setIsCSVButtonLoading(true)
    const requestStatus  = await downLoadCSVFile(queryParams)
    if (requestStatus === 'error') {
      notify.error('something useful for the user')
    }
    setIsCSVButtonLoading(false)
  }, [])
  

 // dans le Dom
  <button disabled={IsCSVButtonLoading} onClick={downloadBookingsCSV}>Download CSV</button>
  
  
```

2021-11-03 10:52 UTC, gael-boyenval commented on src/components/pages/Bookings/PreFilters/PreFilters.jsx
> +    page: 1,
on ne charge qu'une page pour le CSV ?

2021-11-03 11:03 UTC, gael-boyenval requested changes
manque un test pour tout ça :
 
- j'ai bien un bouton
- quand je clique dessus j'appelle bien l'api avec les params XY
- mon bouton est désactivé pendant le chargement
- il se réactive quand le chargement est finit
- j'ai un message d'erreur (notification) si l'api me renvoi autre chose qu'une 200

2021-11-03 11:17 UTC, gael-boyenval commented on src/components/pages/Bookings/PreFilters/PreFilters.jsx
> +              disabled={isLoading}
sauf erreur de ma part, là tu désactive le bouton quand tu charge l'affichage, et non le CSV (ou alors je divague... ce qui est possible)

2021-11-03 11:17 UTC, gael-boyenval commented on src/components/pages/Bookings/PreFilters/PreFilters.jsx
> +              disabled={isLoading}
peut-être dur coup avoir ici un `isTableLoading`, ou quelque chose de plus différenciant que juste isLoading

2021-11-04 08:41 UTC, asagot-ansa commented on src/components/pages/Bookings/PreFilters/PreFilters.jsx
> +    page: 1,
Côté back on s'attend à recevoir le paramètre `page` (car on réutilise `ListBookingsQueryModel` pour les params qu'on attend du front), or il n'a aucun impact sur la génération du CSV, car on récupère automatiquement toutes les pages; donc j'e l'envoie juste pour que le back soit content ;)

2021-11-05 17:21 UTC, rlecellier commented
j'avais une remarque sur l'utilisation de fetch hors de pcapi qui était bloquante pour le merge.

Voici [une PR avec quelques ajouts](https://github.com/pass-culture/pass-culture-pro/pull/1559) afin de ne pas avoir ici un cas particulier d'intéraction avec l'api

2021-11-05 17:21 UTC, closed without merging