(PC-11678) Create formik basic components
pass-culture/pass-culture-pro pull request #1558
Opened 2021-11-05 10:33 UTC by MathildeDuboille

Création des champs compatibles avec `Formik` qui vont être utilisés par le nouveau formulaire d'offres EAC
Ces champs sont sans design dans un premier temps pour ne pas bloquer la création des différents formulaires
Pour tester, utiliser le storybook

2021-11-08 10:28 UTC, gael-boyenval reviewed
1. je me demande si on pourrais pas gérer les erreurs directement dedans 
2. on pourrais faire passer `{...additionalAttributes}` ou un truc comme ça (pour gérer les aria etc)

mais ça peut évoluer dans ce sens plus tard...

2021-11-08 10:44 UTC, gael-boyenval requested changes
autres remarques, je pense que c'est plus dans l'air du temps d'utiliser les hooks => `useFormik`, `useField` etc... mais bon on pourras améliorer/déterminer ça dans une prochaine PR

2021-11-08 10:44 UTC, gael-boyenval commented on src/ui-kit/DurationPicker/DurationPicker.helper.ts
> +export const translateMinutesToHours = (durationInMinutes: number | null): string => {
côté syntaxe, on utilise pas cette norme de `.helper`, en général, soit on a un dossier utils/... ou si la fonction est seule, tu peux directement créer un fichier `translateMinutesToHours.ts`

du coup soit :

`./utils/translateMinutesToHours.ts` 
`./translateMinutesToHours.ts` 
`./utils.ts`


mais je suis pas sûr que se soit comme ça qu'on ai envi de gérer ça de toute façon...

je me demande si c'est pas quelque chose qu'on va gérer directement dans le form, j'aurai tendance à ne garder que les choses hyper standard dans le UI-kit

2021-11-08 10:44 UTC, gael-boyenval commented on src/ui-kit/DurationPicker/DurationPicker.tsx
> +import { Field } from 'formik'
Encore une fois je suis pas sûr que toute cette logique soit à embarquer dans le UI-KIT,
mais si c'est le cas, il faut la tester.

2021-11-08 10:44 UTC, gael-boyenval commented on src/ui-kit/TextInput/TextInput.stories.tsx
> +      )}}
d'une manière générale (valable pour la plutart des champs), je pense qu'on va plutôt utiliser 
```suggestion
    {({ getFieldProps }) => {
      return (
        <TextInput {...getFieldProps('email')}  />
      )}}
```

2021-11-08 10:55 UTC, MathildeDuboille commented on src/ui-kit/DurationPicker/DurationPicker.helper.ts
> +export const translateMinutesToHours = (durationInMinutes: number | null): string => {
Je suis d'accord que le datepicker a beaucoup de logique pour un composant de ui-kit, mais je ne suis pas pour déporter la logique ailleurs car elle est vraiment propre au duration-picker (le fait de formatter l'input avec les `:` par ex). A la limite, on peut mettre le durationPicker dans le dossier components ?

2021-11-08 14:53 UTC, rlecellier reviewed
Ça m'a l'aire bien, j'ai juste quelques questions / propositions sur la forme.

2021-11-08 14:53 UTC, rlecellier commented on src/ui-kit/Checkbox/Checkbox.tsx
> +type CheckboxProps = {
On aura toujours qu'une seul interface de props du coup je propose de toutes les nommé `IProps`
```javascript 
interface IProps = {
// ...
}
```

2021-11-08 14:53 UTC, rlecellier commented on src/ui-kit/Checkbox/Checkbox.tsx
> +type CheckboxProps = {
On à toujours qu'une seul interface de propriété du composant, vu que nous n'avons qu'un seul composant par fichier.
Je propose de toujours utiliser 
```javascript 
interface IProps {
  // ...
}
```

2021-11-08 14:53 UTC, rlecellier commented on src/ui-kit/Checkbox/Checkbox.tsx
> +}) => {
```suggestion
const Checkbox = ({
  name,
  value,
  label,
  className,
}: IProps): JSX.Element => {
```

2021-11-08 14:53 UTC, rlecellier commented on src/ui-kit/RadioButton/RadioButton.stories.tsx
> +          {...getFieldProps('gender')}
indent

2021-11-08 14:53 UTC, rlecellier commented on src/ui-kit/TextArea/TextArea.stories.tsx
> +      )}}
```suggestion
      )}
    }
```

2021-11-08 14:53 UTC, rlecellier commented on src/ui-kit/index.ts
> +export { default as DatePicker } from './DatePicker'
Afin de s'y retrouver lorsqu'on navigue entre les fichiers du projet, je me demande si on ne devrait pas avoir :
* soit un dossier `/ui-kit/form/TextInput`, `/ui-kit/form/TextArea`, etc.
* soit un prefix: `/ui-kit/FormTextInput`, `/ui-kit/form/FormTextArea`, etc.

2021-11-08 15:41 UTC, MathildeDuboille commented on src/ui-kit/Checkbox/Checkbox.tsx
> +type CheckboxProps = {
hmm je ne suis pas entièrement d'accord avec toi, c'est mieux je trouve d'avoir des variables/types/interfaces bien nommées
Le jour où on décide d'exporter l'interface pour l'utiliser ailleurs (ce que j'ai déjà vu sur d'autres projets) on va se perdre avec les `IProps`
On peut passer sur des interfaces si c'est le standard sur PRO mais je préfèferai garder un nommage du style `INomDuComposantProps` si ca te va

2021-11-08 15:48 UTC, MathildeDuboille commented on src/ui-kit/TextArea/TextArea.stories.tsx
> +      )}}
eslint me le corrige de cette façon, la config est peut-être à revoir?

2021-11-09 12:39 UTC, rlecellier commented on src/ui-kit/Checkbox/Checkbox.tsx
> +type CheckboxProps = {
Un nom générique pour les props locale me semble mieux mais c'est peut etre juste une habitude chez moi.

J'ai du mal à voir les cas ou il est utile de récupérer l'interfaces des props d'un composant depuis l’extérieur.
Si c'est quelque chose qu'on est amené à faire alors oui, choisissons `I<ComponentName>Props`

Le seul cas que je vois serait de construire un objet de props à passé en paramètre comme 
```javascript
const myComponentProps: IMyComponentProps = { /* some props */ }
return <MyComponents {...myComponentProps}/>
```
Et encore dans ce cas d'utilisation qui est assez rare, on pourrait avoir 
```javascript
import { IProps as IMyComponentProps } from './**/MyComponent'
```

On vote à la majorité ? xD

2021-11-09 13:58 UTC, MathildeDuboille commented on src/ui-kit/Checkbox/Checkbox.tsx
> +type CheckboxProps = {
@cgaunet @gael-boyenval @gvannest une préférence ?

2021-11-09 16:00 UTC, cgaunet commented on src/ui-kit/Checkbox/Checkbox.tsx
> +type CheckboxProps = {
Préférence sur les interfaces nommées 🖖 
Pas un gros choix ceci dit

2021-11-09 16:23 UTC, gael-boyenval commented on src/ui-kit/Checkbox/Checkbox.tsx
> +type CheckboxProps = {
moi aussi, plutôt du côté des interfaces nommées, en cas d'export et dans l'IDE, c'est plus clair je pense que d'avoir 1000X définitions qui ont le même nom

2021-11-09 16:24 UTC, gael-boyenval commented on src/ui-kit/Checkbox/Checkbox.tsx
> +type CheckboxProps = {
mais pour le coup j'ai tendance à utiliser des interfaces pour les Props = IComponentProps

2021-11-09 16:43 UTC, gael-boyenval approved these changes

2021-11-09 17:31 UTC, gvannest commented on src/ui-kit/Checkbox/Checkbox.tsx
> +type CheckboxProps = {
@MathildeDuboille désolé pour le retard, mais oui interface nommée je suis pour aussi, même si pas de pref forte car pas encore beaucoup de recul sur le front!

2021-11-09 17:45 UTC, rlecellier commented on src/ui-kit/Checkbox/Checkbox.tsx
> +type CheckboxProps = {
j'ai perdu.

2021-11-11 08:50 UTC, merged