Pc 3993 harmonisation input text
pass-culture/pass-culture-pro pull request #673
Opened 2020-08-25 13:20 UTC by asagot-ansa

2020-08-31 16:03 UTC, floragc-octo commented on src/components/pages/Signin/__specs__/Signin.spec.jsx
> +        eyePasswordInput.simulate('click')
invoke

2020-08-31 16:05 UTC, floragc-octo commented on src/components/pages/Signin/__specs__/Signin.spec.jsx
> +        const wrapper = shallow(<Signin {...props} />)
mount et idem un peu plus bas

2020-08-31 16:05 UTC, floragc-octo commented on src/components/pages/Signin/__specs__/Signin.spec.jsx
> +      emailInput.simulate('change', { target: { value: 'un email' } })
invoke

2020-08-31 16:11 UTC, floragc-octo commented on src/components/pages/Signup/SignupForm/SignupForm.jsx
> +  }
```suggestion
  renderEmailTextField = ({ input }) => (
      <TextInput
        label="Adresse e-mail"
        name="email"
        onChange={input.onChange}
        placeholder="nom@exemple.fr"
        required
        sublabel="...pour se connecter et récupérer son mot de passe en cas d’oubli"
        value={input.value}
      />
    )
```

2020-08-31 16:16 UTC, floragc-octo commented on src/components/pages/Signup/SignupForm/SirenField/__specs__/SirenField.spec.jsx
> +describe('src | components | pages | Offerer | OffererCreation | Fields | SirenField', () => {
```suggestion
describe('src | components | SirenField', () => {
```

2020-08-31 16:18 UTC, floragc-octo commented on src/styles/components/layout/inputs/InputText/_InputText.scss
>      padding: 10px 16px;
```suggestion
    padding: rem(10px) rem(16px);
```

2020-08-31 16:19 UTC, floragc-octo commented on src/styles/components/pages/LostPassword/_LostPassword.scss
> +
espace en trop et idem en dessous

2020-08-31 16:20 UTC, floragc-octo commented on src/styles/components/pages/Offerer/_OffererCreationForm.scss
> +    display: flex;
ordre alphabétique SVP

2020-08-31 16:20 UTC, floragc-octo commented on src/styles/components/pages/Offerer/_OffererCreationForm.scss
> +    font-weight: 500;
tutututu on a pas créé les mixins pour rien

2020-08-31 16:21 UTC, floragc-octo commented on src/styles/components/pages/Offerers/_Offerers.scss
> +    display: flex;
dabcefg...

2020-08-31 16:21 UTC, floragc-octo commented on src/styles/components/pages/Profil/_Profil.scss
> +    font-size: 0.9rem;
mixins

2020-08-31 16:22 UTC, floragc-octo commented on src/styles/components/pages/Signin/_Signin.scss
> +    display: flex;
alphabet

2020-08-31 16:22 UTC, floragc-octo commented on src/styles/components/pages/Signin/_Signin.scss
> +      white-space: pre-wrap;
alphabet

2020-08-31 16:26 UTC, floragc-octo reviewed
.

2020-09-01 07:44 UTC, floragc-octo commented on src/components/pages/LostPassword/__specs__/LostPassword.spec.jsx
> +        const wrapper = shallow(<LostPassword {...props} />)
pas possible de faire un mount ?

2020-09-01 07:45 UTC, floragc-octo commented on src/components/pages/LostPassword/__specs__/LostPassword.spec.jsx
> +        const wrapper = shallow(<LostPassword {...props} />)
et sur les suivants

2020-09-01 08:42 UTC, asagot-ansa commented on src/components/pages/Signin/__specs__/Signin.spec.jsx
> +        const wrapper = shallow(<Signin {...props} />)
On ne peut pas mount dans certaines conditions, puisque l'on utilise la méthode wrapper.instance() dans le test et que celle-ci ne fonctionne pas avec un mount.

2020-09-01 08:56 UTC, asagot-ansa commented on src/components/pages/LostPassword/__specs__/LostPassword.spec.jsx
> +        const wrapper = shallow(<LostPassword {...props} />)
Même réponse qu'au dessus rapport aux wrapper.instance()

2020-09-01 13:17 UTC, victorenaud requested changes

2020-09-01 13:17 UTC, victorenaud commented on src/components/layout/inputs/TextInputWithIcon/TextInputWithIcon.jsx
>          className="it-icon"
Pourquoi utiliser "img" et ne pas utiliser notre composant `Icon` ?

2020-09-01 13:36 UTC, victorenaud commented on src/components/pages/LostPassword/LostPasswordContainer.js
> +      requestData({
Est-ce que c'est utile d'utilise dispatch requestData ici ?

2020-09-01 13:36 UTC, victorenaud commented on src/components/pages/LostPassword/LostPasswordContainer.js
> +          requestData({
Est-ce que c'est utile d'utilise dispatch requestData ici ?

2020-09-01 13:36 UTC, victorenaud commented on src/components/layout/form/fields/SirenField/SirenField.jsx
> +              sublabel="obligatoire"
Est-ce qu'on ne veut pas le même affichage partout pour les fields "obligatoires" ?

Dans ce cas cela pourrait être incorporé au TextInput

2020-09-01 13:36 UTC, victorenaud commented on src/components/layout/form/fields/SirenField/__specs__/SirenField.spec.jsx
> +describe('src | components | SirenField', () => {
Je croyais qu'on virait ce type de describe ?

2020-09-01 13:36 UTC, victorenaud commented on src/components/layout/inputs/TextInputWithIcon/TextInputWithIcon.jsx
>    onChange: PropTypes.func,
Renommer `onClick` en `onIconClick`

2020-09-01 13:38 UTC, victorenaud reviewed
Utiliser `wrapper.instance()` est un bad smell
Cela veut dire que vous appelez directement des fonctions, donc vous ne testez pas le comportement réel de la page.
Et en plus vous vous couplez fortement au code.

Normalement il faut utiliser les comportements de la page (click, hover, etc.) plutôt qu'accéder aux fonctions directement

2020-09-01 13:43 UTC, MBrandone commented on src/components/layout/form/fields/PasswordField.jsx
>          <Field
Pour "cela", tu parles du 'name="password"' ? ou Field ?
Pour name, je vais revérifier mais je pense que Field en a besoin pour mapper les valeurs, de chacun des champs.
Pour Field, je pense que ça serait pas cool car Field vient de react-final-form, et ça nous contraindrait à utiliser React-final-form pour tout nos formulaires.
ça nous amènerait aussi à donner deux responsabilités à TextInputWithIcon => l'affichage + potentiellement des règles "métiers" du champs (contraintes de valeurs etc ...)

2020-09-01 13:51 UTC, victorenaud commented on src/components/pages/Profil/Profil.jsx
> +    }else {
Un ptit espace
```suggestion
    } else {
```

2020-09-01 13:51 UTC, victorenaud commented on src/components/pages/Profil/Profil.jsx
> +    return  publicNameInputValue.length < 3 || emailInputValue === ''
Et pour ceux qui ont un nom de moins de 3 caractères ?
Pourquoi cette contrainte ?

2020-09-01 13:51 UTC, victorenaud commented on src/components/pages/Signin/SigninContainer.js
> +      requestData({
Est-ce que c'est utile d'utilise dispatch requestData ici ?

2020-09-01 13:51 UTC, victorenaud commented on src/components/pages/Signin/__specs__/Signin.spec.jsx
> +      eyePasswordInput.invoke('onClick')({ preventDefault: jest.fn() })
À quoi sert le `preventDefault: jest.fn()` ?

2020-09-01 13:51 UTC, victorenaud commented on src/components/pages/Signup/SignupForm/SignupForm.jsx
> +      onChange={input.onChange}
À quoi cela sert ?
Si on le met à chaque fois on ne peut pas le faire par défaut ?

2020-09-01 13:51 UTC, victorenaud commented on src/styles/components/pages/LostPassword/index.scss
> +@import "LostPassword";
Retour à la ligne à la fin du fichier

2020-09-01 13:57 UTC, MBrandone commented on src/components/layout/inputs/TextInputWithIcon/TextInputWithIcon.jsx
>          className="it-icon"
On se questionnait sur l'utilité du composant Icon. Il ne renvoie qu'une balise img avec le bon src en fonction que ce soit un png ou un svg. 
À voir, on l'a pas modifier dans cette PR, vu qu'elle est un peu énorme, on peut le garder en sujet de réflexion, t'en penses quoi ?

2020-09-01 14:21 UTC, MBrandone commented on src/components/pages/LostPassword/LostPasswordContainer.js
> +      requestData({
Dans l'absolu, je dirais non.
C'est la solution la plus rapide qu'on ait trouvé pour enlever pass-culture-shared du composant LostPassword, et que ça continue de fonctionner comme avant. Le composant Form de pass-culture-shared faisait le POST avec requestData.
On a pas voulu chercher plus loin, car ça risque des pousser d'autres optimisations (genre ne pas avoir des fonctions de rappel success et fail en paramètre) et le but de la story était avant tout d'harmoniser visuellement les champs input.

Tu penses qu'on devrait essayer d'y allouer un peu de temps ?

2020-09-01 14:30 UTC, MBrandone commented on src/components/layout/form/fields/SirenField/SirenField.jsx
> +              sublabel="obligatoire"
Avant, on avait un astérisque sur ce champs pour montrer que c'était obligatoire, il a été remplacé par un sublabel obligatoire, car c'est plus "accessible".

Niveau UI, je pense que la tendance est à supprimer les astérisques pour les champs obligatoires (voire même un jour de rendre tout les champs obligatoire pour nous pousser à ne demander que les informations essentielles à l'utilisateur).

Du coup, y a pas encore vraiment de moyen définitif pour afficher qu'un champs est obligatoire. Si y en a un, effectivement, je pense que ça pourrait être incorporé au TextInput.

2020-09-01 14:47 UTC, victorenaud commented on src/components/layout/form/fields/PasswordField.jsx
>          <Field
Je parlais bien de `<Field>` en effet !
Il y a des moments où on ne voudra pas utiliser rest final form ?
Parce qu'actuellement on utilise un Field de cette lib dans tous les endroits modifiés

Mais ok sinon

2020-09-01 14:50 UTC, victorenaud commented on src/components/layout/inputs/TextInputWithIcon/TextInputWithIcon.jsx
>          className="it-icon"
Son seul intérêt est de cacher le `${ROOT_PATH}/icons/${svg}.svg` sous le tapis en effet... :/
A voir si cet intérêt est suffisant.

Perso je pense que ce n'est pas inutile.

2020-09-01 14:50 UTC, victorenaud commented on src/components/pages/LostPassword/LostPasswordContainer.js
> +      requestData({
Dans ce cas, gardez le en mode quickwin
La PR est déjà trop grosse en effet ^^"

2020-09-01 14:51 UTC, victorenaud commented on src/components/layout/form/fields/SirenField/SirenField.jsx
> +              sublabel="obligatoire"
Ok !

2020-09-01 14:53 UTC, MBrandone commented on src/components/pages/Profil/Profil.jsx
> +    return  publicNameInputValue.length < 3 || emailInputValue === ''
Cette contrainte est géré côté API (Je viens de tester sur testing).
On empêche la soumission du formulaire quand ces 3 caractères sont pas respectés, histoire de faire l'appel pour une bonne raison.

2020-09-01 15:05 UTC, MBrandone commented on src/components/pages/Signup/SignupForm/SignupForm.jsx
> +      onChange={input.onChange}
Cette fonction sert de mapping entre le composant graphique pass culture et le composant field de react-final-form. 

Le formulaire de react-final-form stocke les valeurs des différents champs à chaque fois que celui-ci change. Avant, on lui disait de générer un input pour nous, du coup, c'était caché. Maintenant on lui donne le composant React à afficher. Pour que react-final-form continue à fonctionner, il faut lui dire ce qu'il doit écouter pour récupérer les valeurs.

react-final-form donne un exemple ici : https://codesandbox.io/s/40mr0v2r87

2020-09-01 15:49 UTC, MBrandone commented on src/components/layout/inputs/TextInputWithIcon/TextInputWithIcon.jsx
>          className="it-icon"
Je l'ai mi pour voir ce que ça donnait, finalement je pense pas garder le composant Icon.

Le composant Icon a deux propriétés svg et png. Lorsqu'on demande d'afficher une image dans ce composant, on ne sait pas vraiment si c'est un svg ou un png. Du coup, ça induit qu'il faut un peu de logique pour voir si on le met dans la props svg ou png de Icon (ou sinon on se dit qu'on a le droit de passer qu'un certain type d'image pour n'utiliser qu'une props d'Icon).

Je pense que ça restera plus simple si on garde uniquement la balise img pour l'instant, car elle fait le même job avec moins de code.

2020-09-01 15:57 UTC, MBrandone commented on src/components/layout/form/fields/SirenField/__specs__/SirenField.spec.jsx
> +describe('src | components | SirenField', () => {
j'ai gardé 'components | SirenField', pattern qui a l'air d'être utilisé pour les autres tests du genre

2020-09-01 16:10 UTC, MBrandone commented on src/components/pages/Signin/__specs__/Signin.spec.jsx
> +      eyePasswordInput.invoke('onClick')({ preventDefault: jest.fn() })
On a besoin de stubber l'objet evenement lorsqu'on utilise invoke de enzyme. Sinon on se retrouve avec un e.preventDefault is undefined.
Dans le code de prod, ce preventDefault est nécessaire.

2020-09-01 16:30 UTC, victorenaud commented on src/components/pages/Signin/__specs__/Signin.spec.jsx
> +      eyePasswordInput.invoke('onClick')({ preventDefault: jest.fn() })
Mais preventDefault normalement c'est `true` ou `false`

2020-09-01 16:32 UTC, victorenaud approved these changes

2020-09-02 09:29 UTC, NerOcrO requested changes

2020-09-02 09:29 UTC, NerOcrO commented on src/components/pages/LostPassword/LostPassword.jsx
> +                        type="button"
```suggestion
                        type="submit"
```

2020-09-02 09:29 UTC, NerOcrO commented on src/components/pages/LostPassword/LostPassword.jsx
> +  handleToggleHidden = e => {
```suggestion
  handleToggleHidden = event => {
```

2020-09-02 09:29 UTC, NerOcrO commented on src/components/pages/LostPassword/LostPassword.jsx
> +  onHandleSuccessRedirectForResetPassword = () => {
Revoir tous les noms de méthode pour éviter d'avoir onHandle qui n'apporte rien du tout à la compréhension de ce qu'elle fait.

2020-09-02 09:29 UTC, NerOcrO commented on src/components/pages/LostPassword/LostPasswordContainer.js
> +      dispatch(
Problème d'indentation.

2020-09-02 09:29 UTC, NerOcrO commented on src/components/pages/Offerers/Offerers.jsx
> +          value={this.state.keywordsInputValue}
Il faut destructurer le state.

2020-09-02 09:29 UTC, NerOcrO commented on src/components/pages/Offerers/Offerers.jsx
> +      <div className="form-search">
Je pense que tu peux déporter la classe sur le form pour éviter cette div.

2020-09-02 09:29 UTC, NerOcrO commented on src/components/pages/Profil/Profil.jsx
>            <div className="field-profil-input">
```suggestion
```

2020-09-02 09:29 UTC, NerOcrO commented on src/components/pages/Profil/Profil.jsx
> +                type="button"
```suggestion
                type="submit"
```

2020-09-02 09:29 UTC, NerOcrO commented on src/components/pages/Profil/Profil.jsx
>            <div
Tu peux virer les deux div.

2020-09-02 09:29 UTC, NerOcrO commented on src/components/pages/Profil/domain/checkIfEmailIsValid.js
> +export const checkIfEmailIsValid = emailValue => {
```suggestion
export const isEmailIValided = email => {
```

2020-09-02 09:29 UTC, NerOcrO commented on src/components/pages/Signin/Signin.jsx
>                      <div className="field-group">
```suggestion
```

2020-09-02 09:29 UTC, NerOcrO commented on src/components/pages/Signin/Signin.jsx
> +                    <span>
```suggestion
```

2020-09-02 09:29 UTC, NerOcrO commented on src/components/pages/Signin/Signin.jsx
> +                        type="button"
```suggestion
                        type="submit"
```

2020-09-02 09:29 UTC, NerOcrO commented on src/components/pages/Signup/SignupForm/SignupForm.jsx
> +                <div className="field">
Je pense que tu peux t'en passer et overider à chaque fois le label pour ajouter une marge.

2020-09-02 09:29 UTC, NerOcrO commented on src/components/pages/Signup/SignupForm/SirenField/formatSiren.js
> +const formatSiren = input => {
```suggestion
export const formatSiren = input => {
```

2020-09-02 09:29 UTC, NerOcrO commented on src/components/pages/Signup/SignupForm/SirenField/formatSiren.js
> +export default formatSiren
```suggestion

```

2020-09-02 09:29 UTC, NerOcrO commented on src/components/pages/Signup/SignupForm/SirenField/formatSiren.js
> +  return (sirenWithOnlyDigits.match(/.{1,3}/g) || []).join(' ')
J'aurai mis le match dans une constante aussi pour la nommer et je n''ai pas compris le "ou" ?

2020-09-02 09:29 UTC, NerOcrO commented on src/styles/components/pages/Offerer/_OffererCreationForm.scss
> +    align-items: center;
Il faut sauter une ligne après chaque @include.
Je te laisse checker tous les autres.

2020-09-02 09:29 UTC, NerOcrO commented on src/styles/components/pages/Profil/_Profil.scss
> +    padding-right: 0.5rem;
Les remplacer par rem().

2020-09-02 09:29 UTC, NerOcrO commented on src/styles/components/pages/Signin/_Signin.scss
> +    font-weight: $weight-medium;
C'est quelque chose que l'on ne doit plus voir dans notre code, il faut utiliser les mixin mis à disposition dans fonts.scss.
Je te laisse faire une passe globale.

2020-09-02 09:30 UTC, NerOcrO commented
Bonus :
- Peut on éviter les float sur it-sub-label et utilise du flex ?
- Il faut changer name par id sur input.it-input sinon le clic sur le label ne fonctionne pas
- Quand on navigue au clavier, on ne voit pas quand on est sur l'oeil
- Je vois deux fois ".input-text .it-sub-label" dans l'inspecteur

2020-09-02 09:39 UTC, MBrandone commented on src/components/layout/form/fields/SirenField/SirenField.jsx
> +          <div>
C'est vrai, y en a besoin pour satisfaire à `return should have one parent element`.
Je le remplace par un Fragment.

2020-09-02 09:46 UTC, MBrandone commented on src/components/layout/form/fields/SirenField/SirenField.jsx
> +              label="SIREN"
Faudrait voir, je pense qu'on peut en parler en point standard, car ça implique de changer le composant TextInput harmonisé.
Voir de réfléchir à en mettre sur tout les inputs qui en ont besoin, et comment le styliser si besoin.

2020-09-02 10:08 UTC, MBrandone commented on src/components/pages/LostPassword/LostPassword.jsx
> +  onHandleSuccessRedirectForResetPassword = () => {
J'ai renommer en nommant les actions faites dans les fonctions => redirect... ou bien display...

2020-09-02 12:23 UTC, MBrandone commented on src/components/pages/Signin/Signin.jsx
>                      <div className="field-group">
Celui-ci est nécessaire pour du positionnement : regrouper les inputs ensemble en les espacer des liens ensembles.

2020-09-02 12:46 UTC, MBrandone commented on src/components/pages/Signup/SignupForm/SirenField/formatSiren.js
> +const formatSiren = input => {
Je suis + pour le export default afin de pousser à avoir une fonction "util" par fichier.
De plus, ça évite de déstructurer à l'import.

Tu en penses quoi ?

2020-09-02 12:58 UTC, MBrandone commented on src/styles/components/pages/Profil/_Profil.scss
> +    padding-right: 0.5rem;
Pourquoi ? Ils sont bien définis en rem pourtant.

2020-09-02 14:10 UTC, NerOcrO approved these changes

2020-09-02 14:13 UTC, NerOcrO commented on src/styles/components/pages/Profil/_Profil.scss
> +    padding-right: 0.5rem;
Mieux vaut parler en pixel car l'UX parle en pixel donc c'est plus simple à relire.

2020-09-02 14:16 UTC, NerOcrO commented on src/components/pages/Signup/SignupForm/SirenField/formatSiren.js
> +const formatSiren = input => {
Pour le côté une fonction = un fichier, j'suis d'accord.
Par contre, ton IDE fait le taff de la destructuration et il me semble (à vérifier) que lorsque tu renommes une fonction, ton IDE va mieux le faire s'il n'y a pas de default.
De plus, lorsqu'il y a un `export default` et que tu l'importes derrière, tu peux choisir le nom que tu veux. Il m'est déjà arrivé de supprimer une fonction exportée comme ça car j'avais fait une recherche globale sans résultat... ce qui n'était pas vrai au final.

2020-09-03 08:42 UTC, merged