(PC-4199): Add Fnac Provider
pass-culture/pass-culture-pro pull request #705
Opened 2020-09-14 13:54 UTC by floragc-octo

2020-09-16 09:38 UTC, asagot-ansa requested changes

2020-09-16 09:38 UTC, asagot-ansa commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/FnacProviderForm/FnacProviderForm.jsx
> +class FnacProviderForm extends PureComponent {
Puisse-t-on en faire un composant fonctionnel ?

2020-09-16 09:38 UTC, asagot-ansa commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/FnacProviderForm/FnacProviderForm.jsx
> +          <div className="compte-section">
Le français

2020-09-16 09:38 UTC, asagot-ansa commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/FnacProviderForm/FnacProviderForm.jsx
> +              <button
On a pas de bouton harmonisé pour ça ? 😁

2020-09-16 09:38 UTC, asagot-ansa commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/FnacProviderForm/FnacProviderFormContainer.jsx
> +import { getRequestErrorStringFromErrors, showNotification } from 'pass-culture-shared'
On peut virer ça ? :D

2020-09-16 09:38 UTC, asagot-ansa commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/FnacProviderForm/FnacProviderFormContainer.jsx
> +        requestData({
requestData obligatoire ici? Fetch ou autre possible ?

2020-09-16 09:38 UTC, asagot-ansa commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/FnacProviderForm/__specs__/FnacProviderForm.spec.jsx
> +describe('src | components | pages | Venue | VenueProvidersManager | form | LibrairesProviderForm', () => {
Ouh le copié collé

2020-09-16 09:38 UTC, asagot-ansa commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/FnacProviderForm/__specs__/FnacProviderForm.spec.jsx
> +  it('should initialize LibrairesProviderForm component with default state', () => {
shame...

2020-09-16 09:38 UTC, asagot-ansa commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/FnacProviderForm/__specs__/FnacProviderForm.spec.jsx
> +    const wrapper = shallow(<FnacProviderForm {...props} />)
Mount ?

2020-09-16 09:38 UTC, asagot-ansa commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/FnacProviderForm/__specs__/FnacProviderForm.spec.jsx
> +      expect(importButton.prop('className')).toBe('button is-intermediate provider-import-button')
expect une classe :(

2020-09-16 09:38 UTC, asagot-ansa commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/FnacProviderForm/__specs__/FnacProviderForm.spec.jsx
> +      expect(label.text()).toBe('Compte')
Find sur 'Compte' directement

2020-09-16 09:38 UTC, asagot-ansa commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/FnacProviderForm/__specs__/FnacProviderForm.spec.jsx
> +      expect(textField.text()).toBe('12345678912345')
Find sur le texte directement

2020-09-16 09:38 UTC, asagot-ansa commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/FnacProviderForm/__specs__/FnacProviderForm.spec.jsx
> +      const wrapper = shallow(<FnacProviderForm {...props} />)
mount

2020-09-16 09:38 UTC, asagot-ansa commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/FnacProviderForm/__specs__/FnacProviderForm.spec.jsx
> +      const wrapper = shallow(<FnacProviderForm {...props} />)
mount

2020-09-16 09:38 UTC, asagot-ansa commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/FnacProviderForm/__specs__/FnacProviderForm.spec.jsx
> +      const wrapper = shallow(<FnacProviderForm {...props} />)
mount

2020-09-16 09:38 UTC, asagot-ansa commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/FnacProviderForm/__specs__/FnacProviderFormContainer.spec.jsx
> +describe('src | components | pages | Venue | VenueProviderManager | form | ProviderForm', () => {
Ouh le copié collé bis

2020-09-16 09:38 UTC, asagot-ansa commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/FnacProviderForm/__specs__/FnacProviderFormContainer.spec.jsx
> +import { mapDispatchToProps } from '../FnacProviderFormContainer'
spec de container ?

2020-09-16 09:38 UTC, asagot-ansa commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/VenueProviderItem/VenueProviderItem.jsx
> +              {nOffers > 1 ? `${nOffers} offres` : `${nOffers} offre`}
FYI on est en train de rapatrier la fonction pluralize de pc-shared sur pro si vous voulez l'utiliser dans le futur (devrait être mergé dans la journée)

2020-09-16 09:38 UTC, asagot-ansa commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/__specs__/VenueProvidersManager.spec.jsx
> +      const wrapper = shallow(<VenueProvidersManager {...props} />)
mount

2020-09-16 09:38 UTC, asagot-ansa commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/__specs__/VenueProvidersManager.spec.jsx
> +      wrapper.find('#add-venue-provider-btn').simulate('click')
Find sur id :\

2020-09-16 09:38 UTC, asagot-ansa commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/utils/providerOptions.js
> +export const FNAC_PROVIDER_OPTION = {
Est-ce qu'il y aurait moyen de rationaliser avec localProvider de Offer ?

2020-09-16 10:30 UTC, floragc-octo commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/FnacProviderForm/FnacProviderFormContainer.jsx
> +import { getRequestErrorStringFromErrors, showNotification } from 'pass-culture-shared'
exact, on l'a fait dans un des autres composants mais on ne voulait pas tout refactorer tout de suite avant d'avoir de la visu sur tout ce qui est factorisable ! On note

2020-09-16 13:36 UTC, floragc-octo commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/FnacProviderForm/FnacProviderForm.jsx
> +class FnacProviderForm extends PureComponent {
NON !

2020-09-16 13:37 UTC, asagot-ansa commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/FnacProviderForm/FnacProviderForm.jsx
> +class FnacProviderForm extends PureComponent {
ok dsl 🥺

2020-09-16 14:19 UTC, floragc-octo commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/utils/providerOptions.js
> +export const FNAC_PROVIDER_OPTION = {
Je ne connaissais pas ce cas, on va regarder ça !

2020-09-16 15:11 UTC, victorenaud commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/__specs__/VenueProvidersManager.spec.jsx
>          const wrapper = shallow(<VenueProvidersManager {...props} />)
Ce shallow a échappé à la mort, pourquoi ?

2020-09-16 15:11 UTC, victorenaud commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/__specs__/VenueProvidersManager.spec.jsx
> +import { mount, shallow } from 'enzyme'
Il reste des shallows !
#TrouvezLesTous

2020-09-16 15:11 UTC, victorenaud commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/__specs__/VenueProvidersManager.spec.jsx
>          expect(importButton.prop('onClick')).toStrictEqual(expect.any(Function))
Utile ?
Il faudrait plutôt tester le comportement onClick

2020-09-16 15:11 UTC, victorenaud commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/__specs__/VenueProvidersManager.spec.jsx
>        const wrapper = shallow(<VenueProvidersManager {...props} />)
Shallow !

2020-09-16 15:11 UTC, victorenaud commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/__specs__/VenueProvidersManager.spec.jsx
>        const wrapper = shallow(<VenueProvidersManager {...props} />)
Shallow !
https://www.youtube.com/watch?v=JPJjwHAIny4

2020-09-16 15:11 UTC, victorenaud commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/__specs__/VenueProvidersManager.spec.jsx
>        const wrapper = shallow(<VenueProvidersManager {...props} />)
Shallow !

2020-09-16 15:11 UTC, victorenaud commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/__specs__/VenueProvidersManager.spec.jsx
>        const wrapper = shallow(<VenueProvidersManager {...props} />)
Shallow !

2020-09-16 15:11 UTC, victorenaud commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/__specs__/VenueProvidersManager.spec.jsx
>        const wrapper = shallow(<VenueProvidersManager {...props} />)
ˢʰᵃˡˡᵒʷ !

2020-09-16 15:11 UTC, victorenaud commented on src/styles/components/pages/Venue/VenueProvidersManager/LibrairesProviderForm/LibrairesProviderForm.scss
> +  .secondary-button {
Besoin de surcharger l'existant ?

2020-09-16 15:11 UTC, victorenaud commented on src/styles/components/pages/Venue/VenueProvidersManager/TiteliveProviderForm/TiteliveProviderForm.scss
> +    position: absolute;
Besoin de surcharger l'existant ?

2020-09-16 16:09 UTC, apibrac commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/VenueProviderItem/VenueProviderItem.jsx
> +              {nOffers > 1 ? `${nOffers} offres` : `${nOffers} offre`}
Pluralize a l'air un peu trop magique non ?
Une ternary explicite ça a l'air plus pérenne quand même

2020-09-16 16:15 UTC, apibrac commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/FnacProviderForm/FnacProviderForm.jsx
> +class FnacProviderForm extends PureComponent {
Le pure component est à banir
Surtout quand il reçoit des prop "impropres" comme `history`

2020-09-16 16:36 UTC, floragc-octo commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/FnacProviderForm/FnacProviderForm.jsx
> +class FnacProviderForm extends PureComponent {
c'est fait !

2020-09-17 13:12 UTC, floragc-octo commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/FnacProviderForm/__specs__/FnacProviderFormContainer.spec.jsx
> +import { mapDispatchToProps } from '../FnacProviderFormContainer'
C'est de l'historique, on a décidé de les laisser pour l'instant

2020-09-17 13:13 UTC, floragc-octo commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/FnacProviderForm/FnacProviderForm.jsx
> +class FnacProviderForm extends PureComponent {
Au final on a abandonné la tentative parce que react-final-form ne fonctionnait plus correctement.

2020-09-17 13:38 UTC, floragc-octo commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/FnacProviderForm/FnacProviderFormContainer.jsx
> +        requestData({
On conserve l'information dans le store donc a priori besoin du requestData

2020-09-17 14:05 UTC, victorenaud commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/FnacProviderForm/__specs__/FnacProviderForm.spec.jsx
> +      jest.spyOn(props, 'createVenueProvider').mockImplementation((fail, success) => success())
Pourquoi faire un spyOn à posteriori plutôt qu'un jest.fn() qu'on met directement dans les props via un petit props.createVenueProvider = ?

2020-09-17 14:05 UTC, victorenaud commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/FnacProviderForm/__specs__/FnacProviderForm.spec.jsx
> +      jest.spyOn(props, 'createVenueProvider').mockImplementation(fail => fail(null, action))
Pourquoi faire un spyOn à posteriori plutôt qu'un jest.fn() qu'on met directement dans les props via un petit props.createVenueProvider = ?

2020-09-17 14:05 UTC, victorenaud commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/LibrairesProviderForm/__specs__/LibrairesProviderForm.spec.jsx
> +      expect(importButton.prop('className')).toBe('secondary-button')
Expect sur un className ?

2020-09-17 14:05 UTC, victorenaud commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/LibrairesProviderForm/__specs__/LibrairesProviderForm.spec.jsx
> +      jest.spyOn(props, 'createVenueProvider').mockImplementation((fail, success) => success())
Pourquoi faire un spyOn à posteriori plutôt qu'un jest.fn() qu'on met directement dans les props via un petit props.createVenueProvider = ?

2020-09-17 14:05 UTC, victorenaud commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/LibrairesProviderForm/__specs__/LibrairesProviderForm.spec.jsx
> +      jest.spyOn(props, 'createVenueProvider').mockImplementation(fail => fail(null, action))
Pourquoi faire un spyOn à posteriori plutôt qu'un jest.fn() qu'on met directement dans les props via un petit props.createVenueProvider = ?

2020-09-17 14:05 UTC, victorenaud commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/TiteliveProviderForm/__specs__/TiteliveProviderForm.spec.jsx
> +      expect(importButton.prop('className')).toBe('secondary-button')
Tester un class ? Again again ?

2020-09-17 14:05 UTC, victorenaud commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/TiteliveProviderForm/__specs__/TiteliveProviderForm.spec.jsx
> +      jest.spyOn(props, 'createVenueProvider').mockImplementation((fail, success) => success())
Pourquoi faire un spyOn à posteriori plutôt qu'un jest.fn() qu'on met directement dans les props via un petit props.createVenueProvider = ?

2020-09-17 14:05 UTC, victorenaud commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/TiteliveProviderForm/__specs__/TiteliveProviderForm.spec.jsx
> +      jest.spyOn(props, 'createVenueProvider').mockImplementation(fail => fail(null, action))
Pourquoi faire un spyOn à posteriori plutôt qu'un jest.fn() qu'on met directement dans les props via un petit props.createVenueProvider = ?

2020-09-17 14:05 UTC, victorenaud commented on src/styles/components/pages/Venue/VenueProvidersManager/VenueProvidersManager.scss
> +  .libraires-provider-form {
Mais vous avez supprimé la classe `libraires-providerform` non ?

2020-09-17 14:05 UTC, victorenaud commented on src/styles/components/pages/Venue/VenueProvidersManager/VenueProvidersManager.scss
> +      .account-label {
Too much nesting exception non ?
(cf standards)

2020-09-17 14:21 UTC, floragc-octo commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/FnacProviderForm/__specs__/FnacProviderForm.spec.jsx
> +      expect(importButton.prop('className')).toBe('secondary-button')
Non on aurait pu le retirer celui-là au final

2020-09-18 08:35 UTC, floragc-octo commented on src/components/pages/Venue/VenueEdition/VenueProvidersManager/__specs__/VenueProvidersManager.spec.jsx
>          expect(importButton.prop('onClick')).toStrictEqual(expect.any(Function))
Exact, le comportement de ce bouton est testé dans les cas de tests suivants pour chacun des providers donc je retire cette ligne qui n'apporte rien

2020-09-18 09:19 UTC, asagot-ansa approved these changes

2020-09-18 13:07 UTC, merged