(PC-4282): Update API call to activate offer
pass-culture/pass-culture-pro pull request #745
Opened 2020-10-12 14:54 UTC by asagot-ansa

2020-10-13 08:52 UTC, rlecellier commented on src/components/pages/Offers/OfferItem/OfferItem.jsx
> +      })
Il ne me semble pas qu'on execute le refresh quand on desactive ici.
```suggestion
   const toggleOfferStatus =  isActive ? deactivateOffer : activateOffer
   toggleOfferStatus(id).then(() => refreshOffers(false))
```

2020-10-13 08:52 UTC, rlecellier commented on src/components/pages/Offers/OfferItem/OfferItemContainer.js
> +    }),
Ca serait bien d'avoir un fichier `services/pcapi.js` qui regroupe nos appel api, comme j'ai tenter de le faire dans une pr POC ici : https://github.com/pass-culture/pass-culture-pro/pull/743/files#diff-cbbf105b82753decb01149b6aa56db77aa317364d47686939af532dab24bf579

2020-10-13 08:52 UTC, rlecellier commented on src/components/pages/Offers/Offers.jsx
> +    this.getPaginatedOffersWithFilters(true)
Si je comprend bien, on veux un spinner lors du premier chargement mais pas lors des suivant.
Quelquechose comme : 
```
async componentDidMount() {
  this.isBussy = true
  await myAsyncCall()
  await mySecondAsyncCall()
  this.isBussy = false
}
```
Avec `isBussy` qui conditionnne l'affichage du spinner dans le render, ca peut etre plus lisible.

2020-10-13 15:43 UTC, apibrac commented on src/components/pages/Offers/Offers.jsx
> +    this.getPaginatedOffersWithFilters(true)
isBusy ?

2020-10-13 15:44 UTC, apibrac commented on src/components/pages/Offers/Offers.jsx
> +    this.getPaginatedOffersWithFilters(true)
C'est pas mal sync / await ça simplifie bien l'écriture oui
Mais ton `this.isBussy = ...` est un poil cowbow, si isBussy conditionne l'affichage il faut qu'il soit dans un state et setté avec `this.setState({ isBussy: true })`

2020-10-13 16:08 UTC, apibrac requested changes

2020-10-13 16:08 UTC, apibrac commented on src/components/pages/Offers/Offers.jsx
> +          }
pareil je pense que c'est pas vraiment une bonne pratique l'utilisation des callbacks de state mais ça avait l'air déjà là avant

2020-10-13 16:19 UTC, victorenaud commented on src/components/pages/Offers/Offers.jsx
> +          }
Pourquoi ce n'est pas une bonne pratique ?
C'est le seul moyen que tu as qui t'assure que le state a été mis à jour avant.

Dans la méthode `updateUrlMatchingState` le state est utilisé.
Donc si tu le fais sans utiliser de callback, tu utilises le state avant sa mise à jour, et tes données sont fausses

2020-10-13 16:32 UTC, apibrac commented on src/components/pages/Offers/Offers.jsx
> +          }
Dans ce cas précis il faudrait revoir la méthode `updateUrlMatchingState` à mon avis
Elle peut prendre directement en argument les infos de page dont elle a besoin, surtout qu'elle est utilisée que ici donc pas vraiment de raison de contraindre ses arguments (c'est à dire de prendre tout ce qu'elle peut dans le state)

Je pense que c'est une mauvaise pratique parce que react est fait pour être utilisé dans un mode déclaratif, tu écris ce que tu veux obtenir pas comment l'obtenir
Et ce genre de pattern c'est justement l'inverse, c'est de l'impératif, tu écris vraiment les steps les unes après les autres

C'est probablement pour ça que setState ne revoie pas de promise donc ne facilite pas ce genre de pattern
Mais bon après why not hein la feature est là, mais s'il y a d'autres manières de faire ça se débat je pense
Notamment dans notre repo on l'utilise particulièrement souvent (par rapport à mes exp passé donc c'est subjectif) alors qu'il n'y a pas de raison évidente pour que ça arrive plus qu'ailleurs

2020-10-13 16:47 UTC, apibrac commented on src/components/pages/Offers/Offers.jsx
> +          }
Après c'est le genre d'opération qui est faites dans le useEffect maintenant donc les hooks killent le game
Mais du coup peut être que dans le react avec les Component il y a un lifecycle pour ça ? componentDidUpdate ?
J'ai du mal à dire parce que query dans le updateUrlMatchingState est pas dans les proptypes j'ai pas regardé son impact

2020-10-14 09:31 UTC, asagot-ansa commented on src/components/pages/Offers/Offers.jsx
> +    this.getPaginatedOffersWithFilters(true)
En fait, on veut un spinner à l'arrivée sur la page, lors de la recherche / d'un filtre mais PAS, actuellement, lors de l'activation / désactivation de l'offre.
C'est juste un petit hack qu'on a trouvé pour le bien de cette US en attendant l'arrivée du multi-select qui risque de changer la donne.
Pour le moment, quand on clique sur Activer / Désactiver, la liste d'offre se recharge mais sans afficher le loader pour ne pas perturber l'expérience utilisateur. De cette manière, on ne voit que l'offre avec laquelle on a interagit changer de statut.

2020-10-14 09:41 UTC, asagot-ansa commented on src/components/pages/Offers/Offers.jsx
> +      : this.loadAndUpdateOffers(loadOffers, nameSearchValue, selectedVenueId, page)
En fait avec la callback on s'assure à 100% qu'on affichera pas un loader après la réponse (sachant que loadAndUpdateOffer passe isLoading à false quand les données ont étés récupérées); ta proposition est cependant logique étant donnée qu'il y a quasiment 0 risques que le setState à true se fasse après la réponse de l'API (et donc affiche un loader indéfiniment 😢).

WDYT ?

2020-10-14 09:44 UTC, asagot-ansa commented on src/components/pages/Offers/Offers.jsx
> +    loadOffers({ nameSearchValue, selectedVenueId, page })
Exact ! On a aussi pu faire la même manip pour l'utilisation des variables du state :D Merci

2020-10-14 09:51 UTC, asagot-ansa commented on src/components/pages/Offers/Offers.jsx
> +          }
Intéressant comme débat. Si ça te va, je propose qu'on casse tout ce comportement lorsque l'on aura passé nos composants Offers / OfferItem etc en composants fonctionnels (soon soon 😄); on pourra alors utiliser les hooks et la vie sera belle 🌞.

2020-10-14 09:52 UTC, asagot-ansa commented on src/components/pages/Offers/OfferItem/OfferItem.jsx
> +      })
On n'en avait pas le besoin pour cette US précise parce-que le comportement était différent lorsque l'on activait / désactivait (appel API différent, l'un change le state, pas l'autre etc)

Maintenant qu'on a implémenté la désactivation (US 4283); le refresh se fait à l'activation et à la désactivation. :)

2020-10-14 09:54 UTC, asagot-ansa commented on src/components/pages/Offers/OfferItem/OfferItemContainer.js
> +    }),
Dans le ticket 4283, on a refacto notre appel API en l'intégrant dans la fonction fetch existante (utils/fetch.js) que l'on a modifié pour coller aux besoins. 
Ce serait intéressant de discuter de ton point lors des réunions standards cependant !

2020-10-14 10:37 UTC, apibrac commented on src/components/pages/Offers/Offers.jsx
> +      : this.loadAndUpdateOffers(loadOffers, nameSearchValue, selectedVenueId, page)
Je dirais même que c'est impossible que le setState se fasse après non ?
Dans l'idée tu vas dispatch le state `{ isLoading: true }` et ensuite à la fin du load tu dispatch `{ isLoading: false}`
Même s'il n'y avait pas de load donc de laps de temps entre les deux, le false est quand même dispatch après le true
Et comme react va faire les update de state dans l'ordre (même s'il les fait tous d'un coup il est censé respecter l'ordre) ça finira toujours par le dernier donc `{ isLoading: false}`

2020-10-15 14:17 UTC, closed without merging