OfferDetails: add test on read only fields
pass-culture/pass-culture-pro pull request #902
Opened 2020-12-10 10:27 UTC by rlecellier

Ajout de test pour l'edition d'une offre
Et les quelques fixes qui vont avec.

2020-12-11 18:12 UTC, victorenaud requested changes
Il y a un console.log et un cas manquant pour une offre allociné

Par contre tu as pris pas mal de choses que j'avais normalement dans mon ticket, le travail a été fait en double...

2020-12-11 18:12 UTC, victorenaud commented on src/components/pages/Offer/OfferDetails/OfferForm/OfferForm.jsx
> +                />
On pourrait presque sortir ça dans une fonction vu qu'on remet pas mal de fois les même text inputs
Mais ça serait sans doute moins lisible

2020-12-11 18:12 UTC, victorenaud commented on src/components/pages/Offer/OfferDetails/__specs__/OfferCreation.spec.jsx
> +          const musicTypeInput = await getOfferInputForField('musicType')
Est-ce qu'il y a vraiment une valeur ajoutée ?
On se couple à l'implémentation :confused:

2020-12-11 18:12 UTC, victorenaud commented on src/components/pages/Offer/OfferDetails/__specs__/OfferCreation.spec.jsx
> +          await screen.findByLabelText('Genre musical', { exact: false })
À quoi cela sert-il de mettre `exact: false` ici ?

2020-12-11 18:12 UTC, victorenaud commented on src/components/pages/Offer/OfferDetails/__specs__/OfferCreation.spec.jsx
> +      types.push({
Tu peux créer un nouvel array, le push est inutile

2020-12-11 18:12 UTC, victorenaud commented on src/components/pages/Offer/OfferDetails/__specs__/OfferCreation.spec.jsx
> +    expect(descriptionError).toBeNull()
```suggestion
    expect(descriptionError).not.toBeInTheDocument()
```

2020-12-11 18:12 UTC, victorenaud commented on src/components/pages/Offer/OfferDetails/__specs__/OfferEdition.spec.jsx
> +    it('non-sync offers should have some read-only fields', async () => {
```suggestion
    it('should allow edition of editable fields only', async () => {
```
Pour coller avec le `describe` qui est avant

2020-12-11 18:12 UTC, victorenaud commented on src/components/pages/Offer/OfferDetails/__specs__/OfferEdition.spec.jsx
> +    it('sync offers should have only read-only fields', async () => {
```suggestion
    it('should not allow any edition for synchronized offers', async () => {
```

2020-12-11 18:12 UTC, victorenaud commented on src/components/pages/Offer/OfferDetails/__specs__/OfferEdition.spec.jsx
> +    it('sync offers should have only read-only fields', async () => {
Il manque un test pour vérifier que pour une offre allociné l'option duo est modifiable

2020-12-11 18:12 UTC, victorenaud commented on src/components/pages/Offer/OfferDetails/__specs__/helpers.js
> +export const fieldLabels = {
On se couple à l'implémentation avec tout ça

2020-12-14 09:48 UTC, rlecellier reviewed
Le retrait du console log faisait partie d'un morceaux non commité vendredi :(

j'ajoute le comportement sur duo pour les offres allociné

2020-12-14 09:48 UTC, rlecellier commented on src/components/layout/inputs/Errors/InputError.jsx
> +      data-testid={inputErrorTestId}
oui

2020-12-14 09:48 UTC, rlecellier commented on src/components/pages/Offer/OfferDetails/OfferForm/SynchronizableProviderInformation.jsx
> +  )
non, `synchronizableProviders` est un tableaux, `lastProvider.name` n'est pas une clef de l'objet mais doit bien etre rechercher dans les entrées du tableaux.

2020-12-14 09:48 UTC, rlecellier commented on src/components/pages/Offer/OfferDetails/__specs__/OfferCreation.spec.jsx
> +          const musicTypeInput = await getOfferInputForField('musicType')
Pas du tout, RTL vas bien rechercher les élément voulu en utilisant leurs label dans `getOfferInputForField`

2020-12-14 09:48 UTC, rlecellier commented on src/components/pages/Offer/OfferDetails/__specs__/OfferCreation.spec.jsx
> +          await screen.findByLabelText('Genre musical', { exact: false })
Maintenant que les labels des champs contiennent `Optionnelle`, la recherche par label n'est plus exact.

2020-12-14 09:48 UTC, rlecellier commented on src/components/pages/Offer/OfferDetails/__specs__/OfferCreation.spec.jsx
> +      types.push({
C'est vrai, on peut avoir une liste de n éléments avec celui qu'on veux, ca peut etre une liste de 1.
J'avais préféré garder une liste d'options plus grande.

2020-12-14 09:48 UTC, rlecellier commented on src/components/pages/Offer/OfferDetails/__specs__/OfferCreation.spec.jsx
> +    expect(descriptionError).toBeNull()
ca ne fonctionne pas, pour tester la non présence d'un élement dans le document, il faut utiliser `queryBy` puis `toBeNull()`

2020-12-14 09:48 UTC, rlecellier commented on src/components/pages/Offer/OfferDetails/__specs__/OfferEdition.spec.jsx
> +    it('sync offers should have only read-only fields', async () => {
Je vais ajouter ce comportement.

2020-12-14 09:48 UTC, rlecellier commented on src/components/pages/Offer/OfferDetails/__specs__/helpers.js
> +export const fieldLabels = {
On vas chercher les éléments par leurs label, tout comme il RTL.
C'est juste regroupé à un même endroit pour facilement mettre à jours les tests.

2020-12-14 10:11 UTC, victorenaud commented on src/components/pages/Offer/OfferDetails/OfferForm/SynchronizableProviderInformation.jsx
> +  )
Et la suppression du `toLowercase` ?

2020-12-14 10:11 UTC, victorenaud commented on src/components/pages/Offer/OfferDetails/OfferForm/SynchronizableProviderInformation.jsx
> +  )
Et la suppression du `toLowerCase` ?

2020-12-14 10:11 UTC, victorenaud commented on src/components/layout/inputs/Errors/InputError.jsx
> +      data-testid={inputErrorTestId}
Est-ce que ce serait possible d'éviter cela ?

2020-12-14 10:23 UTC, victorenaud approved these changes

2020-12-14 13:22 UTC, rlecellier commented on src/components/pages/Offer/OfferDetails/OfferForm/SynchronizableProviderInformation.jsx
> +  )
On pourrait l'ajouter des deux coté, mais les deux name devrait etre les meme.
A l'inverse d'avant ou on imaginait des clef normalisé en minuscule.

2020-12-14 13:22 UTC, rlecellier commented on src/components/layout/inputs/Errors/InputError.jsx
> +      data-testid={inputErrorTestId}
Je peut mettre une `<span {...} ...extraProps` avec `extraProps` qui continent ou non le test id.

2020-12-14 13:32 UTC, victorenaud commented on src/components/layout/inputs/Errors/InputError.jsx
> +      data-testid={inputErrorTestId}
Ok pour moi !
Et ensuite go merge :smile:

2020-12-14 13:54 UTC, victorenaud approved these changes

2020-12-14 16:52 UTC, merged