WIP - (PC-5132) : add breadcrumb on offer details
pass-culture/pass-culture-pro pull request #917
Opened 2020-12-17 14:47 UTC by rlecellier

Petit PR avant de tout finalisé.
J'ai crée un composant OfferDetails qui regroupe toutes les sous routes d'offres v2.

Il me reste à faire quelques git mv

2020-12-23 17:06 UTC, floragc-octo commented on src/styles/components/pages/Offer/_Breadcrumb.scss
> +    font-weight: 500;
les font-weight et font-size doivent être remplacés par les mixins correspondantes. Si elle n'existe pas, il faut challenger cela avec l'UX.

2020-12-23 17:06 UTC, floragc-octo commented on src/styles/components/pages/Offer/_Breadcrumb.scss
> +      font-weight: 700;
idem pour la mixin

2020-12-23 17:06 UTC, floragc-octo commented on yarn.lock
> +lodash.deburr@^4.1.0:
c'est normal ?

2020-12-28 10:25 UTC, victorenaud requested changes
Le style a sauté pour la mention "Tous les champs sont obligatoires"
Le texte est collé au titre

![image](https://user-images.githubusercontent.com/7222886/103207652-30f2a200-48ff-11eb-83d6-cb0e6409601f.png)


L'édition ne fonctionne pas, j'ai une erreur "Cannot read 'step' of undefined"

2020-12-28 10:25 UTC, victorenaud commented on src/components/pages/Offer/OfferDetails/OfferEdit/OfferForm/OfferForm.jsx
> -
Pourquoi retirer cela d'ici alors que ça dépend du formulaire ?
As-tu vérifié que cela ne cassait pas la mise en forme ?

2020-12-28 10:25 UTC, victorenaud commented on src/components/pages/Offer/OfferDetails/OfferEdit/OfferForm/OfferForm.jsx
> +  setShowMediationForm(displayFullForm)
Ça serait plutôt "showMediationContainer" voire même "showImageUploadContainer"
Je croyais qu'on arrêtait avec le terme "médiation" ?

2020-12-28 10:25 UTC, victorenaud commented on src/components/pages/Offer/OfferDetails/OfferEdit/OfferForm/TypeTreeSelects.jsx
> +          label="Catégorie"
Pourquoi ce changement de nom ?
Normalement ça reste "Type", c'est ce qu'on a dit la dernière fois

2020-12-28 10:25 UTC, victorenaud commented on src/components/pages/Offer/OfferDetails/OfferEdit/__specs__/helpers.js
> -  type: { label: 'Type', exact: true },
Same here pour le changement de nom

2020-12-28 10:25 UTC, victorenaud commented on src/components/pages/Offer/OfferDetails/Stocks/StockItem/StockItem.jsx
> +export const StockItem = ({
```suggestion
const StockItem = ({
```

Un export est apparu sans suppression de l'export default à la fin

2020-12-28 10:25 UTC, victorenaud commented on src/components/pages/Offer/OfferDetails/Stocks/Stocks.jsx
> +      <h3 className="section-title">
Pourquoi modifier ce titre en h3 si le h2 était correct ?

Si `h3.section-title` est notre nouvel h3, il faudrait enlever cette classe et mettre ce style par défaut pour le `h3`, comme pour le reste du styleguide

Est-ce que le style est toujours correct ?

2020-12-28 10:25 UTC, victorenaud commented on src/components/pages/Offer/OfferDetails/Stocks/Stocks.jsx
> -const Stocks = ({ match }) => {
Il faut supprimer le match du container alors
(je suppose le `connect` ?)

2020-12-28 10:25 UTC, victorenaud commented on src/components/pages/Offer/OfferDetails/__specs__/OfferDetails.spec.jsx
> +      Object.defineProperty(window, 'location', {
Utiliser les props permettrait d'éviter cela dans le test... :confused:

2020-12-28 10:25 UTC, victorenaud commented on src/styles/components/pages/Offer/_OfferV2.scss
> +        flex: 0 0 rem(256px);
D'où vient cette valeur ?
Cela fonctionne en responsive ?

2020-12-28 10:25 UTC, victorenaud commented on src/utils/routes_map.jsx
> +      path: '/offres/v2/:offerId(\\w{2})/',
`(\\w{2})/` qu'est-ce que c'est ?

Si c'est une regex qui match 2 mots, je pense qu'elle est incorrecte :thinking:

2020-12-28 10:25 UTC, victorenaud commented on src/components/pages/Offer/OfferDetails/OfferDetails.jsx
>  const OfferDetails = props => {
Si on garde ce système de routing intra composant, alors je reonnemerai cela en `OfferRouter` et renommerai `OfferEdit` en `OfferDetails`

2020-12-28 10:25 UTC, victorenaud commented on src/components/pages/Offer/OfferDetails/OfferEdit/OfferEdit.jsx
> +const OfferDetails = props => {
Comme dit plus haut, je garderai ce nom de composant, et donc renommerai le nom du fichier de `OfferEdit` à `OfferDetail`

2020-12-28 10:25 UTC, victorenaud commented on src/components/pages/Offer/OfferDetails/Stocks/Stocks.jsx
> -      <PageTitle title="Vos stocks" />
Je n'ai pas vu de remplaçant au `PageTitle`
Où est-il passé ?

2020-12-28 10:25 UTC, victorenaud commented on src/components/pages/Offer/OfferDetails/Stocks/Stocks.jsx
> -      <Titles title="Stocks" />
Je n'ai pas vu de remplaçant au `Titles`
Où est-il passé ?

2020-12-28 11:05 UTC, rlecellier reviewed
Quelques reponses et le reste je vais regarder.

2020-12-28 11:05 UTC, rlecellier commented on src/components/pages/Offer/OfferDetails/OfferEdit/OfferForm/TypeTreeSelects.jsx
> +          label="Catégorie"
je suis repassé sur les preview et j'ai changé pour que ca s'accorde. Je n'avais plus en tete qu'on avait validé un Type et nicolux semble mettre à jours les preview reguilièrement.

2020-12-28 11:05 UTC, rlecellier commented on src/components/pages/Offer/OfferDetails/Stocks/Stocks.jsx
> -      <PageTitle title="Vos stocks" />
OfferDetails.js ligne 60

2020-12-28 11:05 UTC, rlecellier commented on src/components/pages/Offer/OfferDetails/Stocks/Stocks.jsx
> -      <Titles title="Stocks" />
OfferDetails.js ligne 60

2020-12-28 11:05 UTC, rlecellier commented on src/styles/components/pages/Offer/_OfferV2.scss
> +        flex: 0 0 rem(256px);
J'ai repris le code existant, juste transferé les css ici.

2020-12-28 11:05 UTC, rlecellier commented on src/utils/routes_map.jsx
> +      path: '/offres/v2/:offerId(\\w{2})/',
ca match 2 lettres

2020-12-28 11:05 UTC, rlecellier commented on yarn.lock
> +lodash.deburr@^4.1.0:
non, j'ai ajouté puis retiré cette dependance ca ne devrait pas etre là.

2020-12-28 12:35 UTC, victorenaud commented on src/components/pages/Offer/OfferDetails/OfferEdit/OfferEdit.jsx
> +        ...oldFormInitialValues,
Je dirai gardons le old, ou alors mettons `previousState` qui a l'air d'être ce qui est communément utilisé
Ou remplaçons `old` par `previous` :D

2020-12-28 12:40 UTC, victorenaud commented on src/styles/components/pages/Offer/_OfferV2.scss
> +        flex: 0 0 rem(256px);
Je ne vois pas d'endroit où ça a été supprimé
Si tu as repris du code existant, tu as oublié de le supprimer ensuite non ?
Si c'était un scss dédié à `sidebar` pourquoi ne pas le garder ?

2020-12-28 12:41 UTC, victorenaud commented on src/utils/routes_map.jsx
> +      path: '/offres/v2/:offerId(\\w{2})/',
Pourquoi faire ?

2020-12-28 13:07 UTC, rlecellier commented on src/utils/routes_map.jsx
> +      path: '/offres/v2/:offerId(\\w{2})/',
on à d'autre route derrière `/offres/v2/`.
afin de distingé `:offer_id` de `/creation` et de `/stocks`, il faut lui donné un format.

2020-12-28 13:56 UTC, rlecellier commented on src/styles/components/pages/Offer/_Breadcrumb.scss
> +      font-weight: 700;
A voir avec @nicolux, on à pas 
```
font-size: rem(16px);
      font-weight: 700;
```

2020-12-28 13:58 UTC, rlecellier commented on src/styles/components/pages/Offer/_OfferV2.scss
> +        flex: 0 0 rem(256px);
OfferPreviewPlaceholder.scss ligne 16

2020-12-28 16:27 UTC, rlecellier commented on src/styles/components/pages/Offer/_Breadcrumb.scss
> +      font-weight: 700;
J'ai utilisé button()
A verifier si ca convient a nicolux d'avoir 600 au lieu de 700

2020-12-28 16:51 UTC, rlecellier commented on src/components/pages/Offer/OfferDetails/OfferDetails.jsx
> +  let currentRoute = offerDetailsRouteMap.find(route => matchPath(currentSubPath, route))
nouvelle solution via un regexp directement sur `location.pathname`

2020-12-28 16:55 UTC, rlecellier commented on src/components/pages/Offer/OfferDetails/OfferEdit/OfferForm/OfferForm.jsx
> -
yep il faut que rebouge ca, c'est une erreur.

2020-12-28 16:57 UTC, rlecellier commented on src/components/pages/Offer/OfferDetails/OfferEdit/OfferForm/TypeTreeSelects.jsx
> +          label="Catégorie"
A revert effectivement

2020-12-28 17:00 UTC, rlecellier commented on src/components/pages/Offer/OfferDetails/Stocks/Stocks.jsx
> +      <h3 className="section-title">
On pourrait virer la classe et l'assigné à tout les h3.

2020-12-28 17:02 UTC, rlecellier commented
todo: git mv les container de *.jsx vers *.js

2020-12-28 17:04 UTC, rlecellier commented on src/components/pages/Offer/OfferDetails/__specs__/OfferDetails.spec.jsx
> +      Object.defineProperty(window, 'location', {
@TODO essayer de retirer window.location

2020-12-31 08:50 UTC, victorenaud approved these changes

2020-12-31 09:13 UTC, merged